### ISSUE TITLE
Possibilidade de usar um equipamento DAF por estabelecimento

### ISSUE THREAD

**Issue by tiagoknipers** [ifsc-lased/daf#1]
### Identificação
- **Nome do responsável:** *Tiago Marcel Knipers*
- **Empresa:** *Megasul Informática Ltda*

### Sugestão:
Capítulo 1 - Introdução (Página 17)
"De acordo com os requisitos apresentados pelo GESAC, cada Ponto de Venda terá um DAF próprio, sendo esse comandado por seu PAF. Dessa forma, entende-se que um contribuinte terá um par PAF e DAF para cada PDV em seu estabelecimento"

A minha sugestão é rever este item, de modo a permitir que, seja possível utilizar 1 equipamento DAF por estabelecimento/contribuinte ao invés de 1 equipamento por PDV, ficando a cargo do desenvolvedor do software e/ou do contribuinte escolher se deseja utilizar um equipamento por PDV ou mais alguns equipamentos para o seu estabelecimento.

O desenvolvedor de software pode realizar o gerenciamento de fila de autorização na rede interna do contribuinte, sem necessidade de acesso a internet disponível para isso, desta forma, suportar que mais de um PDV envie requisições de autorização que serão enfileiradas e processadas em um único equipamento DAF ou mais conforme quantidade de PDVs do estabelecimento X limitações de velocidade de processamento de equipamento.

Exemplo: 
Em uma loja com 10 PDVs, poderia ser atendido com 1 único DAF, uma loja com 30 PDVs, poderia ser atendido por 3 equipamentos. O desenvolvedor de software pode gerenciar as requisições e redirecionar para o equipamento correto.

Se isso for permitido, reduzirá o custo de implantação do DAF significativamente, que é um dos objetivos do Projetos.

Para garantir a segurança, poderia ser adotado um artigo dentro do termo de responsabilidade, assinado pelo desenvolvedor de software, como corresponsável, em caso de eventual detecção de fraude onde o "Software" permitir a realização de uma transação/impressão de comprovante falso ou algo do gênero, sem o devido registro no DAF.

**Comment by edisonbasso** [comment]
> ### Identificação
> * **Nome do responsável:** _Tiago Marcel Knipers_
> * **Empresa:** _Megasul Informática Ltda_
> 
> ### Sugestão:
> Capítulo 1 - Introdução (Página 17)
...

Concordo plenamente, visto que no **Capítulo 1 - Introdução (Página 17)**.
"Essa solução trará os seguintes benefícios aos atores envolvidos:... Contribuinte: Custo total de propriedade reduzido, considerando todos os custos envolvidos durante o ciclo de vida do DAF (aquisição, manutenção e credenciamento);"

**Comment by dennnisk** [comment]
Identificação: Denis Kannenberg

Também concordo com a colocação, permitindo o uso de mais PDV's sobre o mesmo DAF torna o processo mais acessível ao contribuinte, que por consequência torna o processo todo menos burocrático e com menos burocracia mais acessível ao consumidor final que está efetivamente "pagando" a conta.

Uma sugestão, caso o fisco realmente queira controlar cada Ponto de Venda existente no estabelecimento, o PAF possa criar identificadores virtuais para cada Ponto de Venda e registrar no DAF. Assim o DAF estaria permitido emitir o DFe apenas dos pontos registrados. Acredito ser um exagero e desnecessário, porém, geraria um custo de aquisição de equipamentos muito inferior.

**Comment by dopidaniel** [comment]
- Nome do responsável:  Daniel Simões de Almeida
- Empresa: Projeto ACBr

Outro fato, que deve-se levar em conta, é o uso do DAF, em dispositivos onde não seja possível, plugar o mesmo, por falta de Portas USB ou drivers apropriados...

Exemplo: 
Equipamentos como SmartPOS, ou POS TEF, são equipamentos portáteis, e que possuem mini-impressoras... 

Um estabelecimento comercial, poderia usar esses equipamentos moveis, que se conectam por Rede a um Servidor local, onde o DAF está instalado... e dessa maneira, conseguiram emitir Documentos Fiscais válidos...

**Comment by maicoalgeri** [comment]
Identificação: Maico Algeri

Minha Sugestão, é que cada contribuinte utilize um DAF por estabelecimento, por questões de custo e também organização da sequencia de numeração dos documentos fiscais eletrônicos. O contribuinte pode emitir NFCe com a sequencia de numeração controlada pelo estabelecimento, caso tenha mais de um terminal de venda com um DAF cada terminal, isso pode dificultar conferencias e auditorias sobre a sequencia da numeração da NFCe.

**Comment by paulosell** [comment]
> ### Identificação
> * **Nome do responsável:** _Tiago Marcel Knipers_
> * **Empresa:** _Megasul Informática Ltda_
> 
> ### Sugestão:
> Capítulo 1 - Introdução (Página 17)
> "De acordo com os requisitos apresentados pelo GESAC, cada Ponto de Venda terá um DAF próprio, sendo esse comandado por seu PAF. Dessa forma, entende-se que um contribuinte terá um par PAF e DAF para cada PDV em seu estabelecimento"
> 
> A minha sugestão é rever este item, de modo a permitir que, seja possível utilizar 1 equipamento DAF por estabelecimento/contribuinte ao invés de 1 equipamento por PDV, ficando a cargo do desenvolvedor do software e/ou do contribuinte escolher se deseja utilizar um equipamento por PDV ou mais alguns equipamentos para o seu estabelecimento.
> 
> O desenvolvedor de software pode realizar o gerenciamento de fila de autorização na rede interna do contribuinte, sem necessidade de acesso a internet disponível para isso, desta forma, suportar que mais de um PDV envie requisições de autorização que serão enfileiradas e processadas em um único equipamento DAF ou mais conforme quantidade de PDVs do estabelecimento X limitações de velocidade de processamento de equipamento.
> 
> Exemplo:
> Em uma loja com 10 PDVs, poderia ser atendido com 1 único DAF, uma loja com 30 PDVs, poderia ser atendido por 3 equipamentos. O desenvolvedor de software pode gerenciar as requisições e redirecionar para o equipamento correto.
> 
> Se isso for permitido, reduzirá o custo de implantação do DAF significativamente, que é um dos objetivos do Projetos.
> 
> Para garantir a segurança, poderia ser adotado um artigo dentro do termo de responsabilidade, assinado pelo desenvolvedor de software, como corresponsável, em caso de eventual detecção de fraude onde o "Software" permitir a realização de uma transação/impressão de comprovante falso ou algo do gênero, sem o devido registro no DAF.

@tiagoknipers,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

Na versão final desta especificação será adicionada a possibilidade de compartilhamento de um DAF por vários PDVs. Na especificação do DAF serão adicionados os requisitos para tal, porém o total de PDVs por DAF, bem como os requisitos para o PAF operar nesse cenário, serão apresentados em uma especificação específica do PAF-DAF. Deste modo, essa sugestão será acatada.

Novamente, o nosso muito obrigado.
Projeto DAF

**Comment by paulosell** [comment]
> * Nome do responsável:  Daniel Simões de Almeida
> * Empresa: Projeto ACBr
> 
> Outro fato, que deve-se levar em conta, é o uso do DAF, em dispositivos onde não seja possível, plugar o mesmo, por falta de Portas USB ou drivers apropriados...
> 
> Exemplo:
> Equipamentos como SmartPOS, ou POS TEF, são equipamentos portáteis, e que possuem mini-impressoras...
> 
> Um estabelecimento comercial, poderia usar esses equipamentos moveis, que se conectam por Rede a um Servidor local, onde o DAF está instalado... e dessa maneira, conseguiram emitir Documentos Fiscais válidos...

@dopidaniel, como indicado na [resposta acima](https://github.com/ifsc-lased/daf/issues/1#issuecomment-779235015), será adicionada a possibilidade de compartilhar 1 DAF por vários PDVs. Contudo, mesmo sem essa possibilidade verificamos que seria possível conectar diretamente o DAF em dispositivos como o SmartPOS, PayGo C6 e POS Digital (os dois últimos teriam que ofertar a porta USB).

**Comment by paulosell** [comment]
> Identificação: Maico Algeri
> 
> Minha Sugestão, é que cada contribuinte utilize um DAF por estabelecimento, por questões de custo e também organização da sequencia de numeração dos documentos fiscais eletrônicos. O contribuinte pode emitir NFCe com a sequencia de numeração controlada pelo estabelecimento, caso tenha mais de um terminal de venda com um DAF cada terminal, isso pode dificultar conferencias e auditorias sobre a sequencia da numeração da NFCe.

@maicoalgeri, o DAF não fica ciente sobre a sequência de numeração da NFC-e. O único responsável por essa sequência é o PAF-DAF e a especificação deste último está fora do escopo desta consulta pública.
