### ISSUE TITLE
Autenticação em dispositivo USB

### ISSUE THREAD

**Issue by felipesandrini** [ifsc-lased/daf#10]
### Identificação
- **Nome do responsável:** *Felipe Gonçalves Sandrini*
- **Empresa:** *Linx Sistemas e Consultoria LTDA*

### Inconsistência:
*No item 6.2 do manual de especificações e requisitos, é informado a necessidade de se obter um token JWT para realizar uma solicitação de autorização de um DFE, sendo esse token fornecido pelo método de autenticação.

Como o aparelho estará conectado através de uma interface USB em um ambiente local, não seria possível substituir a autenticação por um código de vinculação ou chave fornecida pelo DAF em seu registro? Isso evitará a necessidade de se autenticar diversas vezes no aparelho.

Como sugestão, deveria ser gerada uma chave de vinculação no momento do registro do DAF junto a SEF, utilizando essa chave em substituição ao token JWT. Gostaria de sugerir também a criação de um método que possibilite a troca da chave, permitindo o contribuinte realizar a troca da chave caso o mesmo venha  a perder sua chave original.*

**Comment by jaquerifr** [comment]
> ### Identificação
> * **Nome do responsável:** _Felipe Gonçalves Sandrini_
> * **Empresa:** _Linx Sistemas e Consultoria LTDA_
> 
> ### Inconsistência:
> *No item 6.2 do manual de especificações e requisitos, é informado a necessidade de se obter um token JWT para realizar uma solicitação de autorização de um DFE, sendo esse token fornecido pelo método de autenticação.
> 
> Como o aparelho estará conectado através de uma interface USB em um ambiente local, não seria possível substituir a autenticação por um código de vinculação ou chave fornecida pelo DAF em seu registro? Isso evitará a necessidade de se autenticar diversas vezes no aparelho.
> 
> Como sugestão, deveria ser gerada uma chave de vinculação no momento do registro do DAF junto a SEF, utilizando essa chave em substituição ao token JWT. Gostaria de sugerir também a criação de um método que possibilite a troca da chave, permitindo o contribuinte realizar a troca da chave caso o mesmo venha a perder sua chave original.*

@felipesandrini,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

A "chave de vinculação" citada na contribuição já existe na atual proposta, porém com o nome `chavePAF`. A seção 5.1 da especificação desta consulta pública indica que a SEF, ao confirmar o registro do DAF, gera a `chavePAF`, que deve ser armazenada no DAF e no PAF.  

O DAF não mantém estado sobre as autorizações que gerou, e que já foram autorizadas pela SEF. O uso do nonce no processo de autorização de documentos fiscais, como descrito na Seção 5.2 da especificação desta consulta pública, tem por objetivo proteger o DAF contra ataques de repetição (replay attack). Isso evita que um documento que já foi autorizado pela SEF, e assim não está mais na memória do DAF, possa ser autorizado pela segunda vez pelo DAF.  

As Seções 5.2, 6.2.4, B.3 e o Caso de Uso UC-4.10 da especificação desta consulta pública apresentam detalhes sobre a autorização de DFe. Note que o PAF, para se autenticar junto ao DAF, este não envia um token JWT mas sim um nonce previamente transmitido pelo DAF. Somente a autorização emitida pelo DAF que consiste em um token JWT.

Por fim, na Seção 7.6.5 da especificação desta consulta pública é apresentada a descrição simplificada do processo para recuperar a `chavePAF` junto à SEF. Esse procedimento só pode ser invocado pelo PAF e esse poderá recorrer caso o mesmo venha a perder `chavePAF`.  

Assim sendo, o uso do nonce provê garantias contra alguns tipos de ataques e não gera impacto significativo no processo de autorização de DFe. Além disso, a especificação já apresenta o processo para recuperação da `chavePAF`.


Novamente, o nosso muito obrigado.
Projeto DAF
