### ISSUE TITLE
Dúvidas e Sugestões da empresa Tanca

### ISSUE THREAD

**Issue by TANCA-DAF** [ifsc-lased/daf#11]
### Identificação
- **Nome do responsável:** *Cristiano Abbud*
- **Empresa:** *TANCA*

### Dúvidas:

Na figura 3.1 onde é mostrada a Organização do DAF com seus componentes mínimos não está prevista a utilização de uma Memória Volátil externa. Como se tratam de requisitos “Mínimos” entendemos que poderá ser utilizara uma memória volátil externa, tipo Memória RAM, respeitando as arquiteturas de dados do DAF prevista para as memórias não voláteis. Nosso entendimento está correto?

Na consulta pública disponibilizada não localizamos detalhamento sobre os sistemas ou linguagens de programação permitidas, desta maneira entendemos que fica a critério de cada fabricante definir qual o melhor ambiente de desenvolvimento a ser utilizado e neste caso pode ser o sistema operacional Linux embarcado no DAF. Nosso entendimento está correto?

Item 3.5 - Item 55 – “O gabinete DEVE ser blindado, opaco, sem parafusos aparentes, encaixes e sem a possibilidade de abertura para qualquer tipo de manutenção”.
Gostaríamos de um maior detalhamento sobre este item.
Quando se refere ao gabinete ser "Blindado" esta característica está especificando que o DAF deve conter a "malha de proteção" dos componentes internos do item 57.2. Nosso entendimento está correto? 
Quando se refere ao gabinete "Sem Parafusos Aparentes" esta característica está especificando que o DAF pode conter parafusos para seu fechamento desde que estejam ocultos como por exemplo por uma etiqueta. Nosso entendimento está correto?
Quando se refere ao gabinete "Sem Encaixes" gostaríamos de um maior detalhamento sobre este item uma vez que para qualquer tipo de fechamento de um gabinete com partes eletrônicas há o encaixe das peças para se permitir o fechamento do mesmo.
Caso nossos entendimentos não estejam corretos para o item 55 solicitamos que sejam melhores descritas as especificações mencionadas.

Com relação a interface de comunicação descrita no item 3.7 o DAF deve possuir um "Plugue" USB tipo A ou C para conectar o DAF ao Computador.
Entendemos que este Plugue é utilizado nos casos de um DAF conectado diretamente a porta USB do computador como um dispositivo do tipo "PEN-DRIVE".
Para os casos em que o DAF for um dispositivo periférico conectado ao computador através de um CABO USB entendemos que o cabo deva possuir um "Plugue" tipo A ou C para conectar ao Computador, porém o conector do cabo ao DAF pode ser de livre escolha do fabricante. Nosso entendimento está correto?

**SUGESTÕES DE MODIFICAÇÃO E/OU INCLUSÃO DE PARAMETROS NA ESPECIFICAÇÃO TÉCNICA**

- Considerar a possibilidade de o equipamento DAF permitir a inclusão opcional de interface Wifi e/ou Bluetooth e/ou Ethernet para comunicação entre DAF e PAF permitindo assim a ampla utilização dos novos sistemas web/mobile.

- Permitir o uso de display para mostrar o status do equipamento DAF aos usuários para facilitar o dia a dia dos contribuintes.
Exemplo de aplicação em equipamento fiscal https://www.youtube.com/watch?v=xYmOpSQPBh4 

- Considerar a retirada da malha de proteção do item 57.2 pois uma vez que o processador seguro já contempla sensores de segurança e caso seja utilizada a memória externa a mesma deve trabalhar de maneira criptografada e sendo assim não seria necessário o uso de malha de proteção pois não existem periféricos com informações de segurança desprotegidos.

- Considerar a retirada da chave para detectar a abertura do equipamento do item 57.1 pois uma vez que o processador seguro já contempla sensores de segurança e caso seja utilizada a memória externa a mesma deve trabalhar de maneira criptografada e sendo assim não seria necessário detectar a abertura do gabinete pois não existem periféricos com informações de segurança desprotegidos.

- Considerar para o item 51 a permissão de instalação de toda a parte “Imutável e Mutável” em memória “externa” e criptografada.

- Não encontramos na especificação um detalhamento sobre o tamanho mínimo da Memória de Trabalho.

**Comment by paulosell** [comment]
> ### Identificação
> * **Nome do responsável:** _Cristiano Abbud_
> * **Empresa:** _TANCA_
> 
> ### Dúvidas:
> Na figura 3.1 onde é mostrada a Organização do DAF com seus componentes mínimos não está prevista a utilização de uma Memória Volátil externa. Como se tratam de requisitos “Mínimos” entendemos que poderá ser utilizara uma memória volátil externa, tipo Memória RAM, respeitando as arquiteturas de dados do DAF prevista para as memórias não voláteis. Nosso entendimento está correto?
> 
> Na consulta pública disponibilizada não localizamos detalhamento sobre os sistemas ou linguagens de programação permitidas, desta maneira entendemos que fica a critério de cada fabricante definir qual o melhor ambiente de desenvolvimento a ser utilizado e neste caso pode ser o sistema operacional Linux embarcado no DAF. Nosso entendimento está correto?
> 
> Item 3.5 - Item 55 – “O gabinete DEVE ser blindado, opaco, sem parafusos aparentes, encaixes e sem a possibilidade de abertura para qualquer tipo de manutenção”.
> Gostaríamos de um maior detalhamento sobre este item.
> Quando se refere ao gabinete ser "Blindado" esta característica está especificando que o DAF deve conter a "malha de proteção" dos componentes internos do item 57.2. Nosso entendimento está correto?
> Quando se refere ao gabinete "Sem Parafusos Aparentes" esta característica está especificando que o DAF pode conter parafusos para seu fechamento desde que estejam ocultos como por exemplo por uma etiqueta. Nosso entendimento está correto?
> Quando se refere ao gabinete "Sem Encaixes" gostaríamos de um maior detalhamento sobre este item uma vez que para qualquer tipo de fechamento de um gabinete com partes eletrônicas há o encaixe das peças para se permitir o fechamento do mesmo.
> Caso nossos entendimentos não estejam corretos para o item 55 solicitamos que sejam melhores descritas as especificações mencionadas.
> 
> Com relação a interface de comunicação descrita no item 3.7 o DAF deve possuir um "Plugue" USB tipo A ou C para conectar o DAF ao Computador.
> Entendemos que este Plugue é utilizado nos casos de um DAF conectado diretamente a porta USB do computador como um dispositivo do tipo "PEN-DRIVE".
> Para os casos em que o DAF for um dispositivo periférico conectado ao computador através de um CABO USB entendemos que o cabo deva possuir um "Plugue" tipo A ou C para conectar ao Computador, porém o conector do cabo ao DAF pode ser de livre escolha do fabricante. Nosso entendimento está correto?
> 
> **SUGESTÕES DE MODIFICAÇÃO E/OU INCLUSÃO DE PARAMETROS NA ESPECIFICAÇÃO TÉCNICA**
> 
> * Considerar a possibilidade de o equipamento DAF permitir a inclusão opcional de interface Wifi e/ou Bluetooth e/ou Ethernet para comunicação entre DAF e PAF permitindo assim a ampla utilização dos novos sistemas web/mobile.
> * Permitir o uso de display para mostrar o status do equipamento DAF aos usuários para facilitar o dia a dia dos contribuintes.
>   Exemplo de aplicação em equipamento fiscal https://www.youtube.com/watch?v=xYmOpSQPBh4
> * Considerar a retirada da malha de proteção do item 57.2 pois uma vez que o processador seguro já contempla sensores de segurança e caso seja utilizada a memória externa a mesma deve trabalhar de maneira criptografada e sendo assim não seria necessário o uso de malha de proteção pois não existem periféricos com informações de segurança desprotegidos.
> * Considerar a retirada da chave para detectar a abertura do equipamento do item 57.1 pois uma vez que o processador seguro já contempla sensores de segurança e caso seja utilizada a memória externa a mesma deve trabalhar de maneira criptografada e sendo assim não seria necessário detectar a abertura do gabinete pois não existem periféricos com informações de segurança desprotegidos.
> * Considerar para o item 51 a permissão de instalação de toda a parte “Imutável e Mutável” em memória “externa” e criptografada.
> * Não encontramos na especificação um detalhamento sobre o tamanho mínimo da Memória de Trabalho.

@TANCA-DAF,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação as suas contribuições, temos os seguintes encaminhamentos:

**Dúvida 1.**: Todos os requisitos da organização do DAF são obrigatórios e não mínimos. Assim, a organização deve ser implementada como descrita na especificação, com as possíveis variações que também estão descritas no mesmo documento. Neste sentido, a especificação será revisada para melhor entendimento. Em relação à memória volátil, a especificação contempla os microcontroladores seguros que dispõem de memória volátil integrada ao seu circuito integrado (Veja a discussão na [Contribuição 9](https://github.com/ifsc-lased/daf/issues/9)). A utilização de uma memória volátil externa exigiria requisitos adicionais de segurança tornando o projeto mais custoso.

**Dúvida 2.**: Um sistema operacional como o Linux exige uma Memory Management Unit (MMU) e grande quantidade de Random-access memory (RAM). Nas pesquisas realizadas pela equipe do projeto, não foram encontrados microcontroladores seguros com recursos suficientes (memória RAM integrada) para executar um sistema operacional como o Linux. Sendo assim, a especificação propõe a implementação do DAF apenas com a aplicação e com bibliotecas de suporte, sem sistema operacional.

**Dúvida 3.**: Termo blindado se refere à malha de proteção. O gabinete do DAF deve ser produzido sem encaixes e parafusos de maneira a evitar que o DAF seja aberto e depois fechado sem deixar vestígios. Há alguns processos que permitem a produção de gabinetes com essas características, por exemplo, Epoxi, colas industriais, solda por ultrassom, entre outros. Neste sentido, a documentação será revisada para melhor entendimento.

***Dúvida 4.*/: A especificação do projeto DAF será alterada de modo a especificar que o DAF poderá ter um plugue USB A macho, ou um plugue USB C macho ou uma porta USB C fêmea.

**Sugestão 5.1.**: Está em análise a inclusão da interface de comunicação Bluetooth para o DAF. Contudo, isso não será colocado na primeira versão da especificação do DAF. O projeto foi pensado para ser de baixo custo e adicionar interface ethernet aumentaria a complexidade e o custo do DAF. Contudo, acreditamos que a possibilidade de compartilhar 1 DAF por vários PDVs, poderá atender a necessidade apresentada aqui. 

**Sugestão 5.2.**: O assunto desta sugestão foi tratado na [Contribuição 9, sugestão A5](https://github.com/ifsc-lased/daf/issues/9).

**Sugestão 5.3.**: A malha de segurança é exigida na especificação - apesar da memória criptografada e dos mecanismos anti violação dos microcontroladores seguros - para que não seja necessário exigir certificações que comprovem a segurança dos microcontroladores seguros. Assim, o custo final do DAF é reduzido. A malha de segurança deve ser conectada nos pinos de sensoriamento externos do microcontrolador seguro, possibilitando que este identifique uma tentativa de acesso aos componentes internos do DAF. Este assunto também foi tratado na [Contribuição 9, sugestão A3](https://github.com/ifsc-lased/daf/issues/9).

**Sugestão 5.4.**: A malha de segurança possibilita a detecção de abertura do gabinete. Assim, não é necessário o uso de uma chave como mencionado.

**Sugestão 5.5.**: A especificação exige o uso de um microcontrolador seguro cujos recursos de segurança exigidos pelo DAF já estão embutidos em seu circuito integrado. Desta forma, as regiões de memória descritas no item 51 da especificação não devem ser criadas de forma externa ao microcontrolador seguro. Este assunto também foi tratado na [Contribuição 9, sugestão B6](https://github.com/ifsc-lased/daf/issues/9).

**Sugestão 5.6.**: O tamanho da Memória de Trabalho (MT) é definido pelo fabricante, visando o tipo de estabelecimento que o seu modelo pretende atender. A especificação será mais detalhada a fim de deixar este requisito mais esclarecido.


Novamente, o nosso muito obrigado.
Projeto DAF
