### ISSUE TITLE
PAF-DAF sem necessidade de homologação do Software

### ISSUE THREAD

**Issue by tiagoknipers** [ifsc-lased/daf#2]
### Identificação
- **Nome do responsável:** *Tiago Marcel Knipers*
- **Empresa:** *Megasul Informática Ltda*

### Sugestão:
Conforme apresentada na reunião de consulta pública, o objetivo de se ter um "Hardware", realizando o meio de campo entre o contribuinte e o SEFAZ, é garantir que não haja sonegação fiscal, imputando ao hardware grande responsabilidade nesta solução.

A minha sugestão é que, sendo este o propósito do hardware e também com outro objetivo do "baixo custo" exposto no documento de requisitos, não seja mais necessário a realização de teste de análise funcional do software "PAF" por órgão técnico credenciado. Este processo tem um custo elevado e muita burocracia para ser realizado.

A sugestão é que a Homologação do software PAF-DAF seja substituída por um credenciamento da Software House junto a SEFAZ no S@T e um termo de responsabilidade assinado pela Software House (semelhante ao entregue no processo de homologação do PAF), onde o desenvolvedor concorda em cumprir todos os requisitos fiscais definidos e não desenvolver funções que permitam via software realizar controle fiscal/contábil sem que este deixe de passar pelo Hardware DAF, sob algum tipo de pena ou sanção em virtude de eventual descumprimento.

**Comment by dennnisk** [comment]
Identificação: Denis Kannenberg

Concordo Tiago. Menos burocracia e em caso de descumprimento do PAF este deve sofrer penalidades.

Porém, caso ainda assim queiram manter uma "homologação", sugiro que seja feita de forma online. Ao qual todo os requisitos precisam ser cumpridos na comunicação entre o DAF -> PAF -> FISCO. Ou seja, precisam ser "transmitido" todas as mensagens ao fisco em um ambiente virtual de homologação e após atendidos os requisitos de comunicação, liberar o PAF para o mercado.

Afinal o que interessa realmente é que o PAF cumpra os requisitos técnicos da integração sem falhas.

**Comment by clgraf** [comment]
A homologação como é efetuada hoje de fato é muito burocrática e cara devido ao tempo gasto com a preparação para a homologação dentro da software house e também ao tempo de deslocamento até o órgão homologador, além claro, da homologação propriamente dita.

Por outro lado, não ter homologação permite que aventureiros se motivem a oferecer soluções "duvidosas"

Eu sugiro um meio termo, uma homologação mais simples e objetiva que realmente teste a integração da aplicação comercial com o DAF. Isto dá uma boa segurança também ao desenvolvedor.

Hoje por exemplo, gastamos horas e horas para testar a alteração de registros no banco de dados. Ao meu ver é um requisito inútil quando se tem um hardware, viola as boas práticas de banco de dados, porque para atender o requisito muitas vezes é preciso de-normalizar o banco, gerando overhead em todo a aplicação.

Deveria-se ter também um validador oficial dos arquivos gerados, se é que vão existir. É contra-producente conferir manualmente campo a a campo.

Enfim, são só alguns exemplos que ao meu ver dificultam muito a homologação.

**Comment by jaquerifr** [comment]
> ### Identificação
> * **Nome do responsável:** _Tiago Marcel Knipers_
> * **Empresa:** _Megasul Informática Ltda_
> 
> ### Sugestão:
> Conforme apresentada na reunião de consulta pública, o objetivo de se ter um "Hardware", realizando o meio de campo entre o contribuinte e o SEFAZ, é garantir que não haja sonegação fiscal, imputando ao hardware grande responsabilidade nesta solução.
> 
> A minha sugestão é que, sendo este o propósito do hardware e também com outro objetivo do "baixo custo" exposto no documento de requisitos, não seja mais necessário a realização de teste de análise funcional do software "PAF" por órgão técnico credenciado. Este processo tem um custo elevado e muita burocracia para ser realizado.
> 
> A sugestão é que a Homologação do software PAF-DAF seja substituída por um credenciamento da Software House junto a SEFAZ no S@T e um termo de responsabilidade assinado pela Software House (semelhante ao entregue no processo de homologação do PAF), onde o desenvolvedor concorda em cumprir todos os requisitos fiscais definidos e não desenvolver funções que permitam via software realizar controle fiscal/contábil sem que este deixe de passar pelo Hardware DAF, sob algum tipo de pena ou sanção em virtude de eventual descumprimento.

@tiagoknipers,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

Esta consulta pública buscou tratar o funcionamento e as especificações técnicas do Dispositivo Autorizador Fiscal - DAF. Deste modo, esta sugestão considera processos e definições fora do escopo da atual consulta pública. Os requisitos dos PAF-DAF serão apresentados posteriormente pela SEF. Somente então os processos de credenciamento ou homologação PAF-DAF poderão ser definidos.

Novamente, o nosso muito obrigado.
Projeto DAF
