### ISSUE TITLE
DAF - 3.7 Interface de comunicação - Permitir além da USB comunicação de Rede

### ISSUE THREAD

**Issue by dennnisk** [ifsc-lased/daf#3]
### Identificação
- **Nome do responsável:** Denis Kannenberg
- **Empresa:** JJW Informática Eireli

### Sugestão:
Conforme "3.7 Interface de comunicação", item 62 "O DAF DEVE possuir exclusivamente um conector (plugue) USB-A ou USB-C que permitirá tanto a alimentação do DAF quanto a troca de dados com o PAF." 
Assim como na página 18, "O DAF deverá estar conectado na porta USB do computador onde o PAF será executado." sugere que o DAF deverá estar vinculado a cada PDV, sendo assim dificulta ou impossibilita o desenvolvimento em equipamentos móveis (Celulares, Tablet, etc..).

A sugestão é permitir utilizar um meio de comunicação que seja mais abrangente (e igualmente seguro) permitindo seja possível desenvolver o PAF em ambiente mobile (Tablets, Celulares) o que acaba resultando em menores custos para o Contribuinte, em relação a aquisição de computadores, licença de software.

Não seria substituir a USB, mas permitir que seja utilizado outro meio de comunicação entre o equipamento DAF o PAF que irá comandar a venda.

Faço essa sugestão, porque o mercado de equipamentos está em uma evolução constante. E ao criar uma especificação de um dispositivo em um formato único pode gerar em um futuro próximo a necessidade de adequação ou alteração, fazendo o dispositivo ficar ultrapassado rapidamente.

**Comment by edisonbasso** [comment]
Ótima observação @dennnisk atualmente temos inúmeras empresas migrando para a nuvem, porem se veem de mãos atadas hoje com o PAF-ECF o qual não prevê a utilização por essas aplicações, precisamos evoluir com o DAF neste sentido também.

**Comment by dgessner** [comment]
Identificação: Douglas Gessner

Concordo, acredito que o cenário ideal seria o dispositivo possuir uma interface RJ45 e não necessitar de um computador para o funcionamento, possibilitando a conexão dele diretamente à rede interna ou Internet para funcionar assim como citado acima em smartphones, tablets ou aplicações rodando na nuvem.

**Comment by tiagoknipers** [comment]
Identificação: Tiago Marcel Knipers

Também concordo com as colocações, uma integração com o equipamento via rede RJ45 tornaria o equipamento bem mais eficiente e custos reduzidos em infraestrutura.

**Comment by dennnisk** [comment]
Ao finalizar a análise do documento da consulta pública, na parte de "Apêndices", página 109 em diante, todas as mensagens estão em formato que permite a comunicação via Rede, talvez utilizando o protocolo HTTPS.

Ao meu ver, em termos de controle fiscal, não haverá diferença sobre o modelo proposto e seus controles, pois, o dispositivo será registrado para o Contribuinte que estará vinculado com uma desenvolvedora de Software e seu PAF. Por sua vez o PAF irá gerar na TAG <infAdFisco> a autenticação da operação. Esta autenticação sendo gerada por um dispositivo USB ou um dispositivo central via Rede como sugerido pelo Tiago na issue #1 não fará diferença, gerando o mesmo resultado final.

**Comment by AndreGrassmann** [comment]
Identificação: André César Grassmann

A disponibilização de uso da interface para equipamentos móveis acredito ser imprescindível em 2020. Disponibilizando uma conexão RJ45 pode solucionar este problema tornando acessível a interface para toda rede, reduzindo custo estrutural e facilitando o gerenciamento da interface em um servidor dedicado.

**Comment by karinejung6** [comment]
Identificação: Karine Jung 

Muito importante essa sugestão. Com a evolução dos dispositivos, essa obrigatoriedade do dispositivo USB é um fator limitante no barateamento de custo para o contribuinte.

**Comment by montzzz** [comment]
Identificação: Mateus Tesch Monteiro

Acho válido essa sugestão, como mencionado nos comentários passados, irá se tornar muito mais barato ao cliente final e ficará mais fácil para o desenvolvimento, seria somente encontrar o dispositivo na rede e autorizar o documento.

**Comment by EmersonBarretto** [comment]
- Para termos a possibilidade de usar softwares de ponto de venda embarcados em tablets, celulares ou Smarts POS seria interessante ter uma conexão Bluetooth. 
 - Importante o projeto não limitar os tipos de conexões e ter uma redação que venha a permitir inclusive futuras novas formas de conexões - **só desta forma não estaremos limitando o uso de novas tecnologias no varejo de SC.**

**Comment by paulosell** [comment]
> ### Identificação
> * **Nome do responsável:** Denis Kannenberg
> * **Empresa:** JJW Informática Eireli
> 
> ### Sugestão:
> Conforme "3.7 Interface de comunicação", item 62 "O DAF DEVE possuir exclusivamente um conector (plugue) USB-A ou USB-C que permitirá tanto a alimentação do DAF quanto a troca de dados com o PAF."
> Assim como na página 18, "O DAF deverá estar conectado na porta USB do computador onde o PAF será executado." sugere que o DAF deverá estar vinculado a cada PDV, sendo assim dificulta ou impossibilita o desenvolvimento em equipamentos móveis (Celulares, Tablet, etc..).
> 
> A sugestão é permitir utilizar um meio de comunicação que seja mais abrangente (e igualmente seguro) permitindo seja possível desenvolver o PAF em ambiente mobile (Tablets, Celulares) o que acaba resultando em menores custos para o Contribuinte, em relação a aquisição de computadores, licença de software.
> 
> Não seria substituir a USB, mas permitir que seja utilizado outro meio de comunicação entre o equipamento DAF o PAF que irá comandar a venda.
> 
> Faço essa sugestão, porque o mercado de equipamentos está em uma evolução constante. E ao criar uma especificação de um dispositivo em um formato único pode gerar em um futuro próximo a necessidade de adequação ou alteração, fazendo o dispositivo ficar ultrapassado rapidamente.

@dennnisk,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

Como indicado na resposta da [contribuição 1](https://github.com/ifsc-lased/daf/issues/1), na versão final desta especificação será adicionada a possibilidade de compartilhamento de um DAF por vários PDVs. Sendo assim, imaginamos que atenderemos a necessidade apresentada nesta sugestão.

Novamente, o nosso muito obrigado.
Projeto DAF

**Comment by paulosell** [comment]
> Ótima observação @dennnisk atualmente temos inúmeras empresas migrando para a nuvem, porem se veem de mãos atadas hoje com o PAF-ECF o qual não prevê a utilização por essas aplicações, precisamos evoluir com o DAF neste sentido também.

@edisonbasso, como indicado na [resposta acima](https://github.com/ifsc-lased/daf/issues/3#issuecomment-779236949), será adicionada a possibilidade de compartilhar 1 DAF por vários PDVs.

**Comment by paulosell** [comment]
> Identificação: Douglas Gessner
> 
> Concordo, acredito que o cenário ideal seria o dispositivo possuir uma interface RJ45 e não necessitar de um computador para o funcionamento, possibilitando a conexão dele diretamente à rede interna ou Internet para funcionar assim como citado acima em smartphones, tablets ou aplicações rodando na nuvem.

@dgessner, o projeto foi pensado para ser de baixo custo e adicionar interface ethernet aumentaria a complexidade e o custo do DAF. Contudo, acreditamos que a possibilidade de compartilhar 1 DAF por vários PDVs poderá atender a necessidade apresentada aqui.

**Comment by paulosell** [comment]
> * Para termos a possibilidade de usar softwares de ponto de venda embarcados em tablets, celulares ou Smarts POS seria interessante ter uma conexão Bluetooth.
> * Importante o projeto não limitar os tipos de conexões e ter uma redação que venha a permitir inclusive futuras novas formas de conexões - **só desta forma não estaremos limitando o uso de novas tecnologias no varejo de SC.**

@EmersonBarretto, está em análise a possibilidade de incluir uma interface de comunicação Bluetooth para o DAF. Contudo, isso não será colocado na primeira versão da especificação do DAF.
