### ISSUE TITLE
5.2 - Autorização de Documentos Fiscais Eletrônicos (DF-e) - DAF Responsável por transmitir

### ISSUE THREAD

**Issue by tiagoknipers** [ifsc-lased/daf#4]
### Identificação
- **Nome do responsável:** *Tiago Marcel Knipers*
- **Empresa:** *Megasul Informática Ltda*

### Sugestão:
*Itens 5, 6, 7 e 8 do processo de autorização de documentos fiscais, "O PAF envia o DF-e para a SEFAZ, e solicita a autorização conforme é posto pelo manual do contribuinte do DF-e em questão".

A minha sugestão é que seja atribuído ao DAF a responsabilidade da transmissão do documento fiscal (DF-e) ao SEFAZ, exatamente como ocorre com o SAT, simplificando o processo para o Desenvolvedor do PAF.

Desta maneira, no passo 4, o equipamento receberia um XML já assinado e faria a transmissão do mesmo a SEFAZ, devolvendo a aplicação PAF um arquivo NFC-e autorizado para que seja impresso o DANFE no PDV.

Em caso de indisponibilidade de conexão com a internet/sefaz, o equipamento DAF faria a autorização baseada em seu software básico que possuiria as regras definidas pela SEFAZ/SC, e faria a transmissão do documento de tempos em tempos assim que a conexão fosse reestabelecida.

Caso essa sugestão seja aceita, avaliar também o processo definido como "UC-4.2: Ativar auto-bloqueio" com o intuito rever o modo de autobloqueio, acredito que, em sendo o DAF o responsável pela transmissão, o mais adequado seria não limitar a quantidade de documentos, mas sim baseado no tempo sem comunicação com a SEFAZ, por exemplo, ativar o autobloqueio caso o equipamento DAF não se comunique com o SEFAZ em um prazo de 30/60 dias e apenas se houver algum NFC-e pendente de transmissão.*

**Comment by jaquerifr** [comment]
> ### Identificação
> * **Nome do responsável:** _Tiago Marcel Knipers_
> * **Empresa:** _Megasul Informática Ltda_
> 
> ### Sugestão:
> *Itens 5, 6, 7 e 8 do processo de autorização de documentos fiscais, "O PAF envia o DF-e para a SEFAZ, e solicita a autorização conforme é posto pelo manual do contribuinte do DF-e em questão".
> 
> A minha sugestão é que seja atribuído ao DAF a responsabilidade da transmissão do documento fiscal (DF-e) ao SEFAZ, exatamente como ocorre com o SAT, simplificando o processo para o Desenvolvedor do PAF.
> 
> Desta maneira, no passo 4, o equipamento receberia um XML já assinado e faria a transmissão do mesmo a SEFAZ, devolvendo a aplicação PAF um arquivo NFC-e autorizado para que seja impresso o DANFE no PDV.
> 
> Em caso de indisponibilidade de conexão com a internet/sefaz, o equipamento DAF faria a autorização baseada em seu software básico que possuiria as regras definidas pela SEFAZ/SC, e faria a transmissão do documento de tempos em tempos assim que a conexão fosse reestabelecida.
> 
> Caso essa sugestão seja aceita, avaliar também o processo definido como "UC-4.2: Ativar auto-bloqueio" com o intuito rever o modo de autobloqueio, acredito que, em sendo o DAF o responsável pela transmissão, o mais adequado seria não limitar a quantidade de documentos, mas sim baseado no tempo sem comunicação com a SEFAZ, por exemplo, ativar o autobloqueio caso o equipamento DAF não se comunique com o SEFAZ em um prazo de 30/60 dias e apenas se houver algum NFC-e pendente de transmissão.*

@tiagoknipers,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

O projeto DAF tem como premissa ser um equipamento de baixo custo. Desde modo, é proposto um equipamento passivo que reage a estímulos do PAF, não sendo previstos componentes e protocolos necessários para comunicação direta com os serviços SEFAZ. No entanto, na presente proposta o fluxo de autorização do documento fiscal, do PAF para a SEFAZ, não é alterado. Sendo assim, acreditamos que nesse ponto o projeto DAF não adiciona uma complexidade para os desenvolvedores de PAF. Também foi apresentado um protocolo de comunicação entre o DAF e o PAF-DAF com o intuito de permitir a interoperabilidade com DAF de diferentes fabricantes. Isso permitirá que desenvolvedores do PAF-DAF implementem uma única vez tal protocolo e assim poderá comandar DAF de qualquer fabricante. Deste modo, essa sugestão não será acatada.


Novamente, o nosso muito obrigado.
Projeto DAF
