### ISSUE TITLE
Loping no bootloader - Processo de atualização

### ISSUE THREAD

**Issue by edisonbasso** [ifsc-lased/daf#5]
### Identificação
- **Nome do responsável:** *Edison Antonio Basso*
- **Empresa:** *Desbravador Software LTDA*

### Inconsistência:
*Figura 2.3: Fluxograma do comportamento do bootloader. Página 27*

Visto que no caso de uma **Atualização bem sucedida**  = **Não**, o sistema retorna a executar o processo de atualização a inicialização do DAF fica impedida. A sugestão seria adicionar um fluxo de exceção considerando a criticidade/necessidade de realizar a atualização neste momento.
Deste modo no caso de uma atualização que contenha falhas, as quais não foram possíveis de serem identificadas no laboratório do fabricante o Contribuinte não é penalizado.

![image](https://user-images.githubusercontent.com/74930773/100009642-ec2e9500-2dad-11eb-9919-7465fce8646d.png)

**Comment by paulosell** [comment]
> ### Identificação
> * **Nome do responsável:** _Edison Antonio Basso_
> * **Empresa:** _Desbravador Software LTDA_
> 
> ### Inconsistência:
> _Figura 2.3: Fluxograma do comportamento do bootloader. Página 27_
> 
> Visto que no caso de uma **Atualização bem sucedida** = **Não**, o sistema retorna a executar o processo de atualização a inicialização do DAF fica impedida. A sugestão seria adicionar um fluxo de exceção considerando a criticidade/necessidade de realizar a atualização neste momento.
> Deste modo no caso de uma atualização que contenha falhas, as quais não foram possíveis de serem identificadas no laboratório do fabricante o Contribuinte não é penalizado.
> 
> ![image](https://user-images.githubusercontent.com/74930773/100009642-ec2e9500-2dad-11eb-9919-7465fce8646d.png)

@edisonbasso,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

Uma vez que o DAF for reiniciado para uma atualização de Software Básico, o mesmo não deve voltar para o estado Operação sem que a atualização seja bem-sucedida. Alguns motivos podem resultar em uma falha na atualização do SB, como queda de energia ou algum problema de hardware do DAF. Considerando a existência de um problema de hardware, o DAF poderia ficar infinitamente no loop de atualização de SB. Desta forma, será adicionado como requisito do bootloader do DAF um contador de tentativas de atualização de Software Básico que resultaram em falha. A partir deste contador, caso este atinja um valor pré-definido, o DAF deverá ir para o estado Inutilizado. Esse requisito garante que o DAF não fique inoperante caso ocorra uma queda de energia durante a atualização e garante segurança contra tentativas maliciosas de atualização do Software Básico. 

Novamente, o nosso muito obrigado.
Projeto DAF
