### ISSUE TITLE
6.2 Mensagens da API DAF x Redução de Custos

### ISSUE THREAD

**Issue by tiagoknipers** [ifsc-lased/daf#6]
### Identificação
- **Nome do responsável:** *Tiago Marcel Knipers*
- **Empresa:** *Megasul Informática Ltda*

### Sugestão:
*Tendo em vista que o manual de especificação técnica visa ter um equipamento mais acessível com o objetivo de evitar a sonegação fiscal, porque criar um novo layout? 

Penso que estabelecer um novo layout, diferente de todos os já existentes no mercado, onera o custo para o desenvolvedor PAF e também para o Fabricante do hardware DAF, que terá mais um layout distinto para manter. 

A minha sugestão é que sejam adotados nomes de métodos, parâmetros e layouts iguais aos do equipamento SAT/SP ou algum outro padrão já existente no mercado, penso que isso tornaria mais fácil e simplificada a adoção do DAF tanto para as Software House quanto para o desenvolvedor do hardware que poderia aproveitar todo ou boa parte do que já está desenvolvido.*

**Comment by cantellir** [comment]
Identificação: Rodrigo Cantelli

Concordo com o Tiago.
Se o principal argumento/motivo da SEFAZ/SC é manter o controle (via hardware) e não permitir contingência off-line, me parece que o modelo do SAT/SP cai como uma luva. É algo que já esta validado no mercado e seria de fácil adoção para todo o ecossistema (estabelecimento, revendedor/consultor, fabricantes, desenvolvedor de software) e, claro, para a própria SEFAZ e estado, que não precisaria gerar custos com um novo projeto.
A não ser que o modelo utilizado por SP apresente algum outro gargalo que a SEFAZ/SC considere problema.

**Comment by jaquerifr** [comment]
> ### Identificação
> * **Nome do responsável:** _Tiago Marcel Knipers_
> * **Empresa:** _Megasul Informática Ltda_
> 
> ### Sugestão:
> *Tendo em vista que o manual de especificação técnica visa ter um equipamento mais acessível com o objetivo de evitar a sonegação fiscal, porque criar um novo layout?
> 
> Penso que estabelecer um novo layout, diferente de todos os já existentes no mercado, onera o custo para o desenvolvedor PAF e também para o Fabricante do hardware DAF, que terá mais um layout distinto para manter.
> 
> A minha sugestão é que sejam adotados nomes de métodos, parâmetros e layouts iguais aos do equipamento SAT/SP ou algum outro padrão já existente no mercado, penso que isso tornaria mais fácil e simplificada a adoção do DAF tanto para as Software House quanto para o desenvolvedor do hardware que poderia aproveitar todo ou boa parte do que já está desenvolvido.*

@tiagoknipers,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

O dispositivo SAT-SP não atendeu aos requisitos negociais da Secretaria de Estado da Fazenda de Santa Catarina (SEF), culminando assim no desenvolvimento do projeto DAF. Uma vez que o equipamento DAF possui características diferentes do equipamento SAT, não seria possível a equiparação dos protocolos de comunicação. Entretanto, no projeto DAF não é proposta qualquer alteração nos leiautes da NFC-e e do BP-e. Sendo assim, um PAF que hoje é capaz de lidar com esses DF-e, não precisará sofrer alterações em suas rotinas quando for usar tais documentos com o projeto DAF. Cabe frisar que, a autorização emitida pelo DAF ficará contida no elemento infAdFisco que está presente no leiaute de ambos os documentos. Para um PAF que já opera com o SAT, este precisará implementar rotinas específicas para interagir com o DAF,porém por meio de um protocolo textual e comum aos DAFs de diferentes fabricantes. Deste modo, essa sugestão não será acatada.

Novamente, o nosso muito obrigado.
Projeto DAF
