### ISSUE TITLE
Revisão do Projeto

### ISSUE THREAD

**Issue by emiliana-mkv** [ifsc-lased/daf#7]
### Identificação
- Nome do responsável:Emiliana Kestering 
- Empresa: Damyller 

### Sugestão:

Gostaria muito que essa arquitetura seja repensada e revisada, tanto se fala em inovação e a agilidade que o varejo precisa. E voltamos com uma solução jurássica para algo tão dinâmico que é o varejo! Ninguém quer uma solução frágil, mas oferecer uma solução de hardware em um mundo transformado por soluções cloud, mostra o quanto o governo pensou em como burocratizar e não em
Inovar! demonstra tanta falta de vivência no varejo e negócios digitais, o que nos leva a crer que quem cria essas soluções tem a apenas a vivência da sala de aula ou é um burocrata que fica atrás de uma mesa de cheia de processo e regras. Cadê as soluções para atender a venda mobile, soluções voltadas para omni channel? A solução não traz inovação alguma, apenas complicações, desde quando depender de hardware em uma era digital traz algum benefício para o contribuinte ou para o estado? Quando tecnicamente o que precisamos é apenas de acesso à internet. Foi apresentado um desenho técnico e ultrapassado, me importo com quem aprova esse projeto, sem exigir mais do time técnico. Não queremos fragilidade ou sonegação, pelo contrário queremos inovar de forma segura! Mas, essa solução com esse nome DAF-PAF só mostra o quanto a inovação caminha de forma lenta e em marcha ré. Existe alguma possibilidade de revisão da arquitetura proposta? Minha sugestão é sim ter acadêmicos, auditores, mas também quem está no dia a dia do varejo de grandes redes. Prezados colegas DEV, contribuintes e consumidores estando de acordo, deixe seu comentário para revisão do projeto.

**Comment by dennnisk** [comment]
Identificação: Denis Kannenberg

Concordo que o projeto precisa ser revisado em alguns pontos, principalmente em como esse dispositivo será implantado e utilizado pelo PAF (sistema de gestão) dentro do contribuinte.

Porém, vale lembrar que no varejo (no atendimento ao consumidor final, venda presencial) deve possuir a premissa do ponto de venda sempre estar disponível para a emissão do documento fiscal e para emissão de controles internos da empresa, ou seja, mesmo que não haja a disponibilidade de internet, existe a necessidade de possuir um PDV local na empresa para que seja possível computar uma venda. Mesmo no modelo "omni channel" faz-se necessário atualmente que o softwares e controles rodem localmente, e estes permitam o acesso aos outros canais.

Dito isto, o melhor em termos de custo seria não existir um hardware e apenas um software para atender as necessidades do contribuinte e do estado, ao qual foi sua bandeira (Leia-se NFC-e sem outros controles).

Entendo o lado do fisco aonde a ECF ampliou o controle sobre sonegação fiscal. O ECF apresentou bons resultados. E com os quais eles conseguem ter o embasamento para exigir outro equipamento.

Então a questão principal é, se realmente for imprescindível o uso do DAF, que ele ele seja com o menor custo e com a maior simplicidade possível (Tanto para aquisição, quanto para implementação), a fim de diminuir dos consumidores finais (eu, você e todos nós) esse custo, esse encargo, que todos sabem ser repassado nos custos operacionais de cada empresa.

**Comment by emiliana-mkv** [comment]
Olá Denis,

Porque existe a necessidade de um hardware?? 
Não entendi vejo necessidade. Ou seja novamente eles criam um projeto desconhecendo o dia a dia. Não é só a implantação existe tbm o suporte para redes com mais de 100 caixas, consegue imaginar isso? Treinamento interno, treinamento para vendedores? Enquanto na NFCE tem uma arquitetura muito simples, fácil suporte e manutenção.
Ou seja tem simplificar e encontrar formas de evitar a sonegação, mas nunca voltar a atrás na inovação.

Vc conhece a arquitetura da NFCe sem uso de hardware e ECF? Isso roda em mais 20 estados, mas aqui não funciona. Temos que usar uma solução arcaica!!

**Comment by GilbertoMattos** [comment]
Não vejo necessidade de implementar um novo modelo para tentar controlar o "problema da contingência", pois se uma software house tiver mal intencionada e quiser burlar algum processo ela vai fazer independente do modelo aplicado, inclusive com o DAF-PAF proposto.

Se o problema é a contingência, SC poderia colocar alguns controles a mais no modelo NFC-e já existente, inclusive já tivemos sugestões do próprio fisco em ter uma série especifica para emissão em contingência, isso seria muito melhor do que um modelo totalmente novo.

É totalmente entendível a preocupação com a arrecadação do estado, porem não é apenas uma preocupação do estado de SC e sim de todos os outros estados, o projeto NFC-e da forma que foi concebido atende muito bem os contribuintes e principalmente a arrecadação fiscal, visto que a grande maioria dos estados utilizam este modelo.

O modelo DAF-PAF é pra ter um custo menor que o PAF-ECF atual, mas e o custo com o modelo NFC-e? é muito pequeno comparado com PAF-ECF!

Umas das premissas é utilizar as impressoras fiscais no modelo novo para evitar um custo ainda maior para o contribuinte, vejo que para as empresas ainda é vantajoso "perder" as impressoras fiscais e ter apenas uma impressora não fiscal funcionando em rede. Poderia trocar por exemplo 5 impressoras que custa em media 2.000,00 cada por apenas uma impressora comum de 800,00 que funciona em rede.

enfim, não sei se esta consulta publica tem como objetivo ouvir os contribuintes e repensar o modelo proposto (DAF-PAF), espero que sim, pois um modelo novo alem de colocar complexidade no software(um único para atender vários estados) tem por si só os problemas que surgem em qualquer implementação nova.

**Comment by tiagoknipers** [comment]
Na minha opinião, acredito que o modelo adotado pelo estado do RS/PR e outros com contingência offline é o melhor modelo existente no Brasil. 
A este modelo poderia ser adicionado apenas algum controle de série, ou numeração, ou assinatura digital, por exemplo para evitar que empresas mal intencionadas deixem de enviar as notas em contingência e pronto. Objetivo atingido com baixo investimento.
Inclusive quando saiu na NFC-e o grupo "**Grupo ZD. Informações do Responsável Técnico**", com informações da possibilidade do credenciamento da Software House pelo estado, achei que isso justamente havia sido criado para o estado de Santa Catarina que se posicionava por não abrir mão de conhecer a software house e bloqueá-la se necessário.

**Comment by josielsl** [comment]
Concordo com a @emiliana-mkv, não entendo a necessidade de criar um hardware para garantir a autenticidade da empresa se hoje o projeto da NFC-e funciona tão bem nos demais estados e de forma tão simples. Acredito que esse projeto precisa ser revisto e adequado para os dias atuais. 
Para empresas que utilizam sistemas web é mais prático utilizar o projeto da NFC-e aderido aos demais estados, do que a ideia atual para SC.

**Comment by detinho** [comment]
Identificação: Marcos Vinícius da Silva

Eu também gostaria de entender quais as fraudes esse novo equipamento pretende evitar.

Além disso no início do PDF da consulta pública diz que o projeto tem os seguintes objetivos para cada ator envolvido no processo:
**"Contribuinte: Custo total de propriedade reduzido, considerando todos os custos envolvidos durante o ciclo de vida do DAF (aquisição, manutenção e credenciamento)"**: não cumpriu o objetivo visto que há um custo adicional, o aparelho DAF + customização de software. Uma empresa que já emita NFC-e em outros estados não pode simplesmente aproveitar a solução já existente em seus sistemas, além de ter de adquirir vários novos equipamentos o que demanda novos custos de aquisição, manutenção e treinamento de funcionários.

**"Software House: Simplicidade na criação ou integração do PAF:"** como já mencionado acima, há anos as software house já adaptaram seus sistemas para NFC-e e CF-e-SAT. O CF-e-SAT já foi um retrocesso em relação à NFC-e no modo offline, porém podemos dar um desconto visto que o equipamento é responsável pelo envio à SEFAZ. Novamente, as Software Houses e empresas que possuem software desenvolvido in-house (ou seja, o contribuinte) não poderá aproveitar seu investimento e know-how dos 2 modelos acima em sua plenitude. Sem contar que as UFs que adotaram NFC-e eliminaram os requisitos de PAF por completo (desde requisitos funcionais até homologação).

**"Fabricante de DAF: Margem para agregar funcionalidades e gerar diferentes modelos de
negócio."** Bom aqui vamos concordar que sim. Vai gerar novos negócios para fabricantes. O custo que o contribuinte tem para pagar impostos vai ter parte direcionado pra cá.

**"Objetivo implícito: Estado quer aumentar a arrecadação"**: tudo normal até aqui, faz parte do jogo. Porém como já pontuado em comentários anteriores, quem quer vender sem nota, vai vender sem nota. Ter um "pendrive gourmet" no PC não impede software ou contribuinte de vender sem nota, sinto muito.

Ah, e não vamos esquecer que isso ainda pode gerar alterações em SPED ICMS/IPI e Contribuições, além de outras obrigações acessórias.

Com todos os pontos acima, vejo que o projeto falha na maioria dos seus objetivos e deve ser revisado, ou ainda, o Estado de SC pode adotar um dos modelos já existentes na maioria das UFs brasileiras, sem prejuizo ao Estado, Contribuinte e Software Houses.

E vamos combinar que o modelo NFC-e é muito mais sustentável: menos papel, menos hardware, menos poluição.

**Comment by dennnisk** [comment]
Oi @emiliana-mkv, perdão, talvez não fui tão objetivo ao tentar explicar.

Minha colocação foi: **Prefiro** o projeto sem o equipamento físico (**uso apenas da NFC-e**).
Porém, no varejo **é essencial que o sistema emissor esteja instalado dentro do estabelecimento comercial**, pois, mesmo que fique **sem internet o sistema deve conseguir emitir o documento fiscal de venda a consumidor**. E os sistemas online não tem como realizar a emissão dos documentos ao consumidor, como o @josielsl comentou de sistemas web.

Então, resumindo: O melhor é que seja adotado somente a NFC-e, com a emissão em contingência prevista pela NFC-e.
Porém, mesmo assim, se após essa consulta pública o fisco realmente insistir em manter um equipamento físico para "_gerar mais controle_", então que ele seja mais simples do um equipamento que funcione somente por USB e que não seja obrigatório mais que 1 ou 2 por contribuinte.

**Comment by dopidaniel** [comment]
Eu compreendo e concordo, com a necessidade de um equipamento para a gestão de documentos off-line...
Todos os estados que aderiram a NFCe, já sofrem com usuários que usam a emissão em Off-line, para sonegar...

O mecanismo de emissão em off-line da NFCe, dá muita margem de erro ou fraude. 
- Muitos documentos gerados em off-line possuem erros irrecuperáveis
- O próprio usuário (lojista), pode apagar o HD com os XMLs em Off-line, e a Sw.House não teria como ser solidária
- Muitos softwares não implementam corretamente a contingência Off-line

O fisco vê documentos fiscais represados, como um ativo... e guardar eles em um dispositivo não seguro, como o HD da máquina, é um grande risco...

**Comment by emiliana-mkv** [comment]
Ola @dennnisk 

Vamos lá por parte:


Sobre:

__Minha colocação foi: Prefiro o projeto sem o equipamento físico (uso apenas da NFC-e).
Porém, no varejo é essencial que o sistema emissor esteja instalado dentro do estabelecimento comercial, pois, mesmo que fique sem internet o sistema deve conseguir emitir o documento fiscal de venda a consumidor. E os sistemas online não tem como realizar a emissão dos documentos ao consumidor.__

**Retorno:** No caso grandes redes/caso fiquei sem internet não vende no cartão, porque faz uso de TEF e não de POS, qual comércio hoje sobrevive vendendo apenas no dinheiro, somente quem sonega mesmo. Ou seja, para isso me desculpe, sabe qual problema o DAF resolve nada, só complica a vida de quem faz tudo de forma correta.

**Comment by emiliana-mkv** [comment]
@dopidaniel
Para nós seria um grande avanço realmente se fosse apenas para contingência usar esse equipamento (ultrapassado)
 
Mas Isso não combate sonegação!! 

Consegue detalhar quais seriam os mecanismos de emissão em off-line da NFCe, dá muita margem de erro ou fraude???

Sobre Muitos documentos gerados em off-line possuem erros irrecuperáveis.
Retorno: então podemos usar um validador off line para evitar esses erros, que o proprio estado poderia desenvolver, seria muito interessante para as equipes de DEV inclusive.

Sobre: O próprio usuário (lojista), pode apagar o HD com os XMLs em Off-line, e a Sw.House não teria como ser solidária.
Retorno: já ouviram falar em Gcloud, amazon, vc pode compartilhar uma pasta do disco C fazer backup a cada 5 minutos, a falta de conhecimento de de 5% compromete os outros 95%.

Sobre: Muitos softwares não implementam corretamente a contingência Off-line
Retorno: Qual % o percentual disso?? falando genericamente assim, sem dado nenhum, informação nenhuma é relevante.

Posso fazer a mesma consideração!! o Projeto NFC-e de outros estados que *não* usam equipamentos ou seja em torno de 25 estados é o melhor, e impossível de sonegar, percebe que minha afirmação e atua tem o mesmo peso.

A Sefaz pode colocar prazo de 24 horas no máximo, depois bloqueia o contribuinte. São tantas formas para chegar a uma solução técnica para contingência, mas de novo até o momento NADA do que foi dito justifica o uso do equipamento.
E SPED serve para que??
E obrigações que adquirentes entregam x informações NFC-e XML ??
E as tag CNPJ Adquirente na NFC-e foi criada para que??

**Comment by emiliana-mkv** [comment]
Pessoal,
Vamos lá Twitter tb, chega de sempre concordar com esses projetos sem justificativa técnica, sem dados nenhum! Queremos sim um projeto que o estado e os estabelecimentos estejam de acordo, se o problema é a contingência podemos dar inúmeras sugestão de controle!!! Menos o onerar o contribuinte com mais um equipamento e uma impressora! Vamos inovar a favor da sustentabilidade e chega de hardwares ultrapassados!  
ifsc_saojose.

**Comment by dennnisk** [comment]
> **Retorno:** No caso grandes redes/caso fiquei sem internet não vende no cartão, porque faz uso de TEF e não de POS, qual comércio hoje sobrevive vendendo apenas no dinheiro, somente quem sonega mesmo. Ou seja, para isso me desculpe, sabe qual problema o DAF resolve nada, só complica a vida de quem faz tudo de forma correta.

Um exemplo único, no caso de Grandes Redes não refletem ou outros 80% dos contribuintes, geralmente médios e pequenos. Comércios de bairro recebem em dinheiro, aceitam cheque ou mesmo outros ramos de atividades de porte um pouco maior, que suas vendas se baseiam em conta (a exemplo o comércio de auto-peças que 40% da venda é a emissão de boletos, etc).

Se você pensar apenas nas Capitais e grandes cidades como SP ou Florianópolis realmente a possibilidade de ficar sem internet é ínfima. Agora para outras cidades menores aonde existe apenas uma operadora de internet essa possibilidade existe, e para este contribuinte possuir a emissão localmente, eu considero imprescindível. Não somente para atender a legislação, mas para controle interno do contribuinte.

Claro, vai da interpretação e decisão de cada empresa de software, mas, temos aqui a gestão na nuvem e as emissões de documentos fiscais instalados localmente dentro dos contribuintes. Um modelo que sempre atendeu bem, claro que inicialmente desenvolvido por exigência do fisco, mas que se mostrou válido e plausível.

**Comment by emiliana-mkv** [comment]
@dennnisk 

Então porque o  fisco/estado considera a venda NF (55) como isento de sonegação e o modelo NFCE (65) devido a contingência, existe margem para sonegação, certo?? 
Se for isso então muda a arquitetura NFC-e -> Webservice e uso do dispositivo para apenas contingência.

A contingência segue a mesma numeração da nota normal, ou seja, não podem existir lacunas. O contribuinte terá que pelo menos inutilizar essa numeração de nota, ao invés de aprovar a contingência, seria esse tipo de sonegação? Mas, se isso acontece pelo número de inutilização, poderia existir algum controle??

Ou contribuinte, pode trabalhar mais de que 24h sem internet, a NFC-e é realidade em mais de 25 estados, e está ocorrendo em comércios menores e locais, estão todos usando. Os demais governos estão criando programa de incentivos, como é o exemplo de São Paulo, onde o contribuinte pode cadastrar a nota e concorre ao prêmios mensais. Fazendo projetos em que o cliente exija a nota fiscal, que é uma medida que realmente consegue evitar a sonegação.

Comércio de bairro tendo que adquirir equipamentos e softwares houses precisam desenvolver sistema complexos, com várias regras, etc.. tudo isso, não faz sentido contra sonegação. 

Esse seu exemplo de ficar sem internet, mostra como o projeto não faz sentido, celular todos tem neh, alias tem + no Brasil do que gente. Então, imagina ter o app para conseguir realizar a venda, afinal estamos falando de pagamentos via PIX, carteiras digitais, cartões virtuais, novas formas de pagamentos. Realmente com sinal 3G já basta para comunicar um webservice e aprovar a nota, tendo a possibilidade de mostrar um QR code tem tela para o consumidor tem o número da nota, que obrigatoriamente a contingência exige, mas não ao invés disse ele precisa de um notebook ou computador conectado em outro hardware para vender, porque não existe outra forma de controlar a contingência ... é uma piada neh!! 

E ainda em algum momento terá que que ter acesso a internet banda larga, talvez mais caro que o plano de celular, porque precisa transmitir os documentos do DAF para a SEFAZ.

Sobre: . Um modelo que sempre atendeu bem, claro que inicialmente desenvolvido por exigência do fisco, mas que se mostrou válido e plausível.

RETORNO: Um modelo que funciona sim, não estou dizendo que não funciona. Estou dizendo que existem outros melhores e com visão para DIGITALIZAÇÃO dos pagamentos, inovação, venda mobile, vida sem impressora, ou seja, que funcionam MELHOR.

**Comment by dgessner** [comment]
> Ola @dennnisk
> 
> Vamos lá por parte:
> 
> Sobre:
> 
> **Minha colocação foi: Prefiro o projeto sem o equipamento físico (uso apenas da NFC-e). Porém, no varejo é essencial que o sistema emissor esteja instalado dentro do estabelecimento comercial, pois, mesmo que fique sem internet o sistema deve conseguir emitir o documento fiscal de venda a consumidor. E os sistemas online não tem como realizar a emissão dos documentos ao consumidor.**
> 
> **Retorno:** No caso grandes redes/caso fiquei sem internet não vende no cartão, porque faz uso de TEF e não de POS, qual comércio hoje sobrevive vendendo apenas no dinheiro, somente quem sonega mesmo. Ou seja, para isso me desculpe, sabe qual problema o DAF resolve nada, só complica a vida de quem faz tudo de forma correta.

Identificação: Douglas Gessner

Retorno: O fato não é só não ter acesso à Internet, pode simplesmente o webservice estar fora do ar, e ter um equipamento de contingência local para a rede toda permitiria a continuidade das operações. Mas vamos supor que caia a Internet mesmo, OK, não prossegue a venda por cartão, porém as vendas em dinheiro vivo e os crediários continuam funcionando, não é a operação normal mas já resolve bastantes problemas dependendo o tipo de comércio.

Em outra colocação você disse "Esse seu exemplo de ficar sem internet, mostra como o projeto não faz sentido, celular todos tem neh, alias tem + no Brasil do que gente. Então, imagina ter o app para conseguir realizar a venda, afinal estamos falando de pagamentos via PIX, carteiras digitais, cartões virtuais, novas formas de pagamentos. Realmente com sinal 3G já basta para comunicar um webservice e aprovar a nota, tendo a possibilidade de mostrar um QR code tem tela para o consumidor tem o número da nota, que obrigatoriamente a contingência exige, mas não ao invés disse ele precisa de um notebook ou computador conectado em outro hardware para vender, porque não existe outra forma de controlar a contingência ... é uma piada neh!!"

Retorno: Recentemente tivemos um evento climático que destruiu redes elétricas e de telecomunicações, em minha cidade a VIVO por exemplo demorou em torno de 5 dias para retornar ao seu funcionamento normal, talvez você diga que com uma tragédia o comércio também não estaria trabalhando.... porém é bastante comum acontecerem estragos por enchentes, trovoadas, tornados, granizo, etc.... e os primeiros comércios que mesmo afetados devem suprir a população, são materiais de construção, mercados, farmácias, etc... então sem uma contingência local, não terão como vender. Reitero a minha opinião que acho interessante sim, ter no máximo 2 equipamentos destes por cliente atuando para a validação via rede local por conexão RJ45 e este equipamento fica responsável pelo envio ao Governo do Estado, assim pode-se usar celular, tablet, computador ou seja lá qual for o dispositivo que quiser para a venda propriamente dita, basta este dispositivo estar conectado em rede local. O que é inaceitável e eu concordo com você é o fato de nesse projeto eles exigirem que esse equipamento esteja conectado por USB a um computador, isso nos dias atuais não se aplica.

**Comment by detinho** [comment]
A questão toda é que já existe NFC-e offline em um modelo que já funciona e mais econômico. Esse aparelho é só mais um custo e ponto de falha. SEFAZ irá obrigar contribuinte a ter aparelho reserva? Quantos? Se o aparelho der defeito, como proceder? Lembrando que grandes redes podem absorver ou repassar esse custo facilmente... mas e os pequenos comerciantes?
Outro questionamento: se no RJ por exemplo, toda a rede de internet parar de funcionar é possível continuar emitindo como NFC-e offline correto? Ou tem algo que impeça a emissão NFC-e offline no modelo atual?

O SAT em SP já é um absurdo, tendo em vista que já existe o modelo NFC-e offline. Porém ao menos o SAT cuida da transmissão dos documentos. Se adotassem o **mesmo modelo** de SP já seria um avanço, sem reinventar a roda novamente. 
Podem até rebatizar se quiserem, mas simplifiquem a vida dos contribuintes por favor!

**Comment by emiliana-mkv** [comment]
Pessoal,

- Para quem não conhece, esse é o modelo/arquitetura da NFCe contingência, que funciona em todos
estados, exceto SC.


https://drive.google.com/file/d/184JzU6NKHe5fvsWJEEgwlWJiv9JVMFZk/view?usp=drivesdk

![image](https://user-images.githubusercontent.com/74941895/101850994-90983180-3b39-11eb-827c-799697b56a8a.jpeg)

**Comment by emiliana-mkv** [comment]
Para quem desconhece, segue imagem do fluxo simples para emitir uma NFCE. Em outros estados. 
O pessoal aqui foi criativo em burocratizar e querer empurrar um equipamento para o contribuinte hein!! Meus parabéns 
![image](https://user-images.githubusercontent.com/74941895/101853032-b8899400-3b3d-11eb-824b-de0fe8c6d0f9.jpeg)

**Comment by MarceloLagoSoares** [comment]
Pessoal, respeito o comentário de todos e vou deixar também a minha opinião.
Trabalho em uma Software House séria que faz software **sem sonegação** e diariamente perdemos negócios para os concorrentes que não são sérios e sempre tem uma "tecla mágica" para entrar em modo de sonegação.
Isso ocorre porque muitos clientes pedem isso (infelizmente), inclusive pedem pra nós e preferimos não fazer.
Espero que este não seja o caso de vocês, mas enfrento isso todos os dias e prefiro dormir tranquilo.

Quem **não sonega** vai continuar **não sonegando**, mas a NFC-e hoje é um "prato cheio" pra quem quer sonegar pois é muito fácil, e principalmente no modo off-line.
Isso se comprova pela arrecadação dos estados que em nada melhorou após a entrada da NFC-e como é hoje, permitindo facilmente a sonegação.

Portanto se a secretaria da fazenda de SC prefere colocar um hardware pra bloquear a fraude eu dou total apoio.
O mesmo com relação a homologação do PAF pois somente empresas sérias irão homologar seu software e querer se manter no mercado.
E o fato de termos que desenvolver um software especifico pra SC é até melhor pois irão abrir novas oportunidades de negócio.
Espero inclusive que o DAF se estenda pra todos os estados.

Abs
Marcelo

**Comment by dgessner** [comment]
> Pessoal, respeito o comentário de todos e vou deixar também a minha opinião.
> Trabalho em uma Software House séria que faz software **sem sonegação** e diariamente perdemos negócios para os concorrentes que não são sérios e sempre tem uma "tecla mágica" para entrar em modo de sonegação.
> Isso ocorre porque muitos clientes pedem isso (infelizmente), inclusive pedem pra nós e preferimos não fazer.
> Espero que este não seja o caso de vocês, mas enfrento isso todos os dias e prefiro dormir tranquilo.
> 
> Quem **não sonega** vai continuar **não sonegando**, mas a NFC-e hoje é um "prato cheio" pra quem quer sonegar pois é muito fácil, e principalmente no modo off-line.
> Isso se comprova pela arrecadação dos estados que em nada melhorou após a entrada da NFC-e como é hoje, permitindo facilmente a sonegação.
> 
> Portanto se a secretaria da fazenda de SC prefere colocar um hardware pra bloquear a fraude eu dou total apoio.
> O mesmo com relação a homologação do PAF pois somente empresas sérias irão homologar seu software e querer se manter no mercado.
> E o fato de termos que desenvolver um software especifico pra SC é até melhor pois irão abrir novas oportunidades de negócio.
> Espero inclusive que o DAF se estenda pra todos os estados.
> 
> Abs
> Marcelo

Concordo plenamente com você, muito se tem olhado pelo lado do contribuinte (e eu falo aqui como um), porém se for apenas analisar por esse ponto, pra mim o melhor seria até eu ter que enviar os dados somente no final do mês, seria muito melhor... Porém do ponto de vista do fisco isso não é interessante e abre margem para sonegação, assim como a contingência da NFC-e, e é aí que entra pelo menos 1 hardware validador, que seria o responsável por validar os documentos e enviar ao Fisco, pois a informação ficaria guardada nele e sem a possibilidade de ser deletada. Entendo perfeitamente que colocar um equipamento no meio do caminho gera um custo para o contribuinte, entendo também que a estrutura do NFC-e já está pronta e as Software Houses não teriam um custo a mais para desenvolver mais uma aplicação para atender SC, porém como o Marcelo citou muito bem, existem fragilidades no NFC-e e SC tem a chance de corrigir isso e é pra isso que estamos colocando os pontos de vista nesse espaço. Quanto ao contribuinte existe um meio de não onerar ele com o custo do equipamento que seria um abatimento do mesmo do ICMS que ele deve pagar, assim o Estado poderia pagar digamos em 12 parcelas o valor desse validador  descontando do ICMS a ser pago pelo contribuinte, pelo menos na aquisição do primeiro equipamento... é utópico, porém seria o caminho ideal. O importante nisso tudo é que haja uma solução que seja de fácil implementação, barata, evite a sonegação e funcione mesmo com falta de Internet ou instabilidade de serviços, acredito que é isso que todos estamos em busca.

**Comment by detinho** [comment]
Vamos dar um passo atrás. As SEFAZ criam esse mecanismos (NFC-e com QRCode, "prêmios" como nota paulista, nota legal, etc) para que o consumidor faça o trabalho de fiscalização, pois é óbvio que o estado não tem recursos para fiscalizar todos os estabelecimentos.
Portanto o consumidor pode consultar a validade do documento junto à SEFAZ via QRCode ou extrato de "prêmios". Caso não encontre o documento pode cobrar o estabelecimento (já vi acontecer, bizarro) ou efetuar uma denúncia.

Sendo assim, o modelo NFC-e online e offline cumprem seu papel, pois se dentro do prazo legal o documento não aparece nas consultas de interesse do consumidor o mesmo pode tomar alguma ação.

Então vamos para o exemplo da tecla mágica (com ou sem, S/N, etc): caso o estabelecimento deseje não recolher os tributos, irá usar a tecla mágica para vamos dizer 50% de suas vendas diárias. No momento da realização de venda com tecla mágica o sistema simplesmente irá pular todas as rotinas de NFC-e. O sistema não irá nem ao mesmo emitir um documento offline e deixar de enviá-lo à SEFAZ. Realiza uma impressão qualquer e dá ao cliente.
Ou ainda pode simplesmente nem passar a mercadoria pelo sistema e receber o valor diretamente do cliente.
Ou ainda pode usar sua criatividade... não há limites.

Agora vamos usar esse mesmo sistema de tecla mágica com o DAF. Basta que o sistema não acesse o aparelho, realize uma impressão qualquer e dê ao cliente. Ou receber diretamente. Mesmo caso acima.

Em ambos os casos um consumidor que desejar pode realizar a conferência e posterior cobrança e denúncia do estabelecimento. Sem diferença.
A única forma de o estado eliminar / reduzir a sonegação é que o consumidor faça o trabalho de fiscalização. As duas alternativas técnicas chegam ao mesmo resultado. Mas com a óbvia diferença de aumento de custos e burocracias.

Houve também argumentos sobre a guarda dos documentos offline. O contribuinte tem que manter os arquivos dos documentos emitidos fora de contingência e de NF-e também, então já é algo dado, já está no seu fluxo de trabalho.

Sobre novas oportunidades de negócio, sinto discordar mais uma vez: isso é apenas custo. Novas oportunidades de negócio geram mais valor ao cliente, reduzem custos e geram riqueza. Esse projeto realiza exatamente o contrário, exceto para os fabricantes dos aparelhos como já mencionei em comentários anteriores. Porém eu tinha entendido que o projeto visava beneficiar os contribuintes e consumidores.

Sabe uma forma bacana de reduzir a sonegação: reduzir os impostos de tal forma que não compense mais sonegar. Todo mundo sai ganhando: maior arrecadação, menos tributos para um estabelecimento, preços mais baixos, etc. Ou seja mais riqueza na sociedade. Quanto maior a alíquota, maior o prêmio para o sonegador (sob a ótica de risco x retorno).

**Comment by detinho** [comment]
Aos colegas que compartilham da minha opinião: sabemos que no final das contas, teremos que nos adaptar, pois com o estado não há concorrência direta e ainda há o monopólio da força, portanto resta nos adaptarmos e absorver os custos. Mas o importante dessas discussões não será o resultado desse caso concreto mas sim um novo rumo e atitudes que estamos tomando.
Obrigado a todos pela discução.

**Comment by dennnisk** [comment]
@emiliana-mkv , @dgessner , @detinho .

Acredito que a NFC-e ira cumprir toda a necessidade, sem a necessidade de um aparelho. E programas de "recompensa" ao consumidor final que cadastra os cupons, servindo como um "fiscal" ajudaria muito a evitar a sonegação.
E @detinho , diminuir a carga tributária combatendo os gastos desnecessários do governo (salários acima da média, aposentadorias especiais, compras com má fiscalização, etc, etc, etc...) e com melhor administração ajudaria muito a mais a evitar a sonegação do que um mero dispositivo fiscal, porém, vejo esse caminho como uma utopia...

Também vale lembrar que se o contribuinte quiser sonegar, ele simplesmente não passa a venda pelo PDV e nada fica registrado, então, o programa de "recompensa" ao consumidor final acaba sendo muito útil para evitar sonegação.

Porém caso o Estado realmente deseje optar por um dispositivo, que seja o menos custoso possível ao Contribuinte que já possui encargos demais.

@emiliana-mkv e volto a comentar, concordo com 90% da sua visão, exceto que seja permitido a instalação do software que faz a emissão do documento fiscal fora do domicílio do contribuinte. Não precisa ser instalado todo o software de gestão dentro da empresa, falo especificamente da parte que irá emitir o documento fiscal destinado a consumidor final.
Ou seja, o PDV deve rodar dentro do contribuinte. Mas é muito, muito importante que esse emissor (PDV) possa ser um software rodando em qualquer dispositivo, seja um celular, tablet, "modem", computador desktop, notebook, relógio, etc, etc, etc...

Digo isso porque em uma das poucas vezes que fui a outro estado, ouvi a atendente da empresa aonde estava adquirindo uma mercadoria falar que não poderia entregar o cupom porque estava sem internet e sem o sistema "da nuvem". É inaceitável sair com um papel anotado a caneta o valor da compra...

**Comment by maicoalgeri** [comment]
Minha visão própria sobre o PAF-ECF e agora sobre DAF-PAF, sempre defendidos por Santa Catarina, é como uma "Tornozeleira Eletrônica" colocada na perna do contribuinte como se ele fosse um criminoso, mesmo ele sendo contribuinte sério e honesto. O estado de Santa Catarina deveria adotar a NFCe nacional e seguir como exemplo, Paraná, São Paulo, Mato Grosso, Espirito Santo, que devolvem parte do ICMS e sorteia prêmios para incentivar todo consumidor a pedir a Nota Fiscal. Menos Custo e menos Burocracia para o comerciante.

**Comment by paulosell** [comment]
> ### Identificação
> * Nome do responsável:Emiliana Kestering
> * Empresa: Damyller
> 
> ### Sugestão:
> Gostaria muito que essa arquitetura seja repensada e revisada, tanto se fala em inovação e a agilidade que o varejo precisa. E voltamos com uma solução jurássica para algo tão dinâmico que é o varejo! Ninguém quer uma solução frágil, mas oferecer uma solução de hardware em um mundo transformado por soluções cloud, mostra o quanto o governo pensou em como burocratizar e não em
> Inovar! demonstra tanta falta de vivência no varejo e negócios digitais, o que nos leva a crer que quem cria essas soluções tem a apenas a vivência da sala de aula ou é um burocrata que fica atrás de uma mesa de cheia de processo e regras. Cadê as soluções para atender a venda mobile, soluções voltadas para omni channel? A solução não traz inovação alguma, apenas complicações, desde quando depender de hardware em uma era digital traz algum benefício para o contribuinte ou para o estado? Quando tecnicamente o que precisamos é apenas de acesso à internet. Foi apresentado um desenho técnico e ultrapassado, me importo com quem aprova esse projeto, sem exigir mais do time técnico. Não queremos fragilidade ou sonegação, pelo contrário queremos inovar de forma segura! Mas, essa solução com esse nome DAF-PAF só mostra o quanto a inovação caminha de forma lenta e em marcha ré. Existe alguma possibilidade de revisão da arquitetura proposta? Minha sugestão é sim ter acadêmicos, auditores, mas também quem está no dia a dia do varejo de grandes redes. Prezados colegas DEV, contribuintes e consumidores estando de acordo, deixe seu comentário para revisão do projeto.

@emiliana-mkv,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

O projeto DAF foi guiado pelo [Ajuste SINIEF 15/18](https://www.confaz.fazenda.gov.br/legislacao/ajustes/2018/AJ0015_18), o qual especifica que a emissão e autorização da Nota Fiscal de Consumidor Eletrônica (NFC-e) em Santa Catarina será realizada por meio de equipamento desenvolvido e autorizado para uso fiscal, comandado por meio de programa aplicativo desenvolvido por empresa credenciada pela respectiva administração tributária. Logo, os questionamentos propostos nesta sugestão, quanto a necessidade da utilização de hardware, encontram-se fora do escopo da presente consulta pública. Deste modo, essa sugestão não será acatada.

Novamente, o nosso muito obrigado.
Projeto DAF
