### ISSUE TITLE
Requisito de uso de microcontrolador seguro

### ISSUE THREAD

**Issue by otavio** [ifsc-lased/daf#8]
### Identificação
- **Nome do responsável:** Otavio Salvador
- **Empresa:** ELGIN S/A

### Inconsistência:

Na especificacao, leia-se:

![image](https://user-images.githubusercontent.com/25278/101629382-05ffe700-3a00-11eb-89d8-9705e3f2f1ad.png)

mas nao deixa claro se o uso de microcontrolador / microprocessador que tem suporte a verificacao de assinatura de bootloader eh requirido ou se somente o bootloader estar em memoria protegida eh suficiente para atender a especificacao.

**Comment by jaquerifr** [comment]
> ### Identificação
> * **Nome do responsável:** Otavio Salvador
> * **Empresa:** ELGIN S/A
> 
> ### Inconsistência:
> Na especificacao, leia-se:
> 
> ![image](https://user-images.githubusercontent.com/25278/101629382-05ffe700-3a00-11eb-89d8-9705e3f2f1ad.png)
> 
> mas nao deixa claro se o uso de microcontrolador / microprocessador que tem suporte a verificacao de assinatura de bootloader eh requirido ou se somente o bootloader estar em memoria protegida eh suficiente para atender a especificacao.

@otavio,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação a sua contribuição, temos o seguinte encaminhamento:

A especificação em questão visa os microcontroladores seguros, que possuem, entre outros recursos, a funcionalidade de verificação de assinatura do bootloader. Além disso, nesta especificação, exige-se a verificação, pelo bootloader, da integridade e autenticidade do Software Básico. Desta forma, o esclarecimento solicitado será melhor detalhado na especificação final do DAF.

Novamente, o nosso muito obrigado.
Projeto DAF
