### ISSUE TITLE
Contribuições Técnicas DAF

### ISSUE THREAD

**Issue by Juridico-afrac** [ifsc-lased/daf#9]
Lúcia Correia da Silva 
Diretora Departamento Jurídico
AFRAC - Associação Brasileira de Automação para o Comércio

Tendo em vista a publicação da Consulta Pública através do Ato DIAT Nº 047/2020 e a publicação das especificações de requisitos do equipamento DAF (Dispositivo Autorizados Fiscal), os Grupos Técnicos de Trabalho da AFRAC passaram a análise do mesmo e apresentam as seguintes sugestões e questionamentos:

**A.	SUGESTÕES TÉCNICAS:**

**1)**	Sobre Interface USB, relativos aos itens 2, 3, 3.4, 3.5, 3.7, 6.3:
**a.**	A interface USB é uma solução que obriga à presença física junto ao PDV, com conexão direta em painel ou através de cabos extensores e hubs. No caso de dispositivos PDV móveis, essa conexão deixa de ser possível, uma vez que dispositivos móveis possuem, tipicamente, apenas uma porta USB, com capacidade limitada de fornecimento de energia e mecanicamente inapropriada para conexão de um equipamento como apêndice.
**b.**	Entende-se que deveria ser permitido que a interface física pudesse ser implementada através de um dos padrões, além do USB: BLUETOOTH, WI-FI e ETHERNET.
**c.**	Como consequência, torna-se necessário permitir que o DAF possa ser acessado remotamente pelo PDV, podendo estar em local afastado, mas ainda fisicamente dentro do endereço do contribuinte.
**d.**	Em adição, em verdade, o fabricante poderia ainda escolher mais de uma interface ao mesmo tempo, podendo, por exemplo, que o DAF possa ser conectado diretamente à USB ou acessado via BLUETOOTH.
**2)**	Sobre o modelo de negócio 1 DAF para 1 PDV:
**a.**	Segundo o documento, todo terminal PDV, dotado de um aplicativo PAF, deve ter um DAF próprio.
**b.**	Sugerimos que um DAF seja compartilhado opcionalmente entre alguns PDVs, podemos ter um número máximo, como 5.
**3)**	Sobre a blindagem do equipamento:
**a.**	O documento utiliza o texto “malha” para se referir à blindagem no requisito 56.1. No entanto, isto encarece a solução, embora traga segurança adicional, neste cabe saber se a blindagem é um requisito mínimo. Sugerimos que poderia ser exposto apenas o requisito de segurança, ficando cada fabricante com a incumbência de demonstrar ao Órgão Técnico a eficácia da solução que está propondo.
**4)**	Sobre os Drivers de Comunicação CDC:
**a.**	Para as plataforma Linux, concordamos com a SEFAZ.
**b.**	Mas para plataforma Windows, essa categoria de drivers não apresenta uma solução nativa adequada pois os drivers oferecidos pelo Windows tem apresentado problemas em PDVs, em especial com relação à compatibilidade com as funções de suspensão e economia de energia deste sistema operacional.
**c.**	Desta forma, gostaríamos que, pensando na segurança do contribuinte, a SEFAZ abra para que Fabricantes possam fornecer Drivers próprios para comunicação com o DAF, respeitando claramente o requisito de exposição de porta serial para o PAF.
**5)**	Sobre a interface visual:
**a.**	Entendemos que a interface visual é muito importante para fins de suporte técnico do dispositivo e que limitar a apenas um LED possa restringir essa operação.
**b.**	Entendemos que, pensando no suporte, o fabricante deveria ter ao menos um indicador, conforme especificado no documento, mas mantendo ao seu critério a existência de outros indicadores auxiliares que possam contribuir para operação e suporte.
**c.**	A existência de outros indicadores auxiliares passa então a ser uma tomada de decisão estratégica do fabricante, em termos de custos e benefícios para o contribuinte.
**d.**	Outro ponto importante seria não definir a tecnologia do indicador. O mercado oferece diversas opções visuais, inclusive displays digitais. Restringir isso não parece ter conexão com segurança e deveria ser uma decisão de custo e benefício que cabe ao Fabricante.
**6)**	Identificamos um possível problema em caso de erro de comunicação numa das etapas do processo de autorização do DF-e, sendo que não há especificação para um possível procedimento de recuperação. Acreditamos que seja necessária uma pequena revisão neste processo.
**7)**	Sobre Bootloader e Programa do Modo Violado, gostaríamos de solicitar que houvesse a possibilidade de atualização também, assim como pode ser atualizado o aplicativo do DAF.

**B.	QUESTIONAMENTOS LEVANTADOS:**

**1)**	Qual seria a expectativa de mercado para o DAF em SC?
**2)**	Qual a previsão da infraestrutura de recebimento dos cupons estar pronta para o DAF? 
**3)** O estado de Santa Catarina considera que o fabricante que tiver pronto um protótipo poderia testar nesse tempo? Assim que esta infraestrutura estiver pronta e um contribuinte deseja instalar o DAF em produção, será possível ou somente em 2022?
**4)**	Quando estaria disponível o ambiente de desenvolvimento para que os fabricantes já possam validar o software básico?
**5)**	Já existe algum produto referência que os fabricantes pudessem ver o funcionamento? Caso positivo poderíamos ter acesso à documentação desse produto referência?
**6)** Visando produzir um equipamento de menor custo, é necessário esclarecer quanto ao boot seguro e confirmar se é necessário o uso de processador com suporte a boot seguro e bootloader assinado ou se somente o bootloader em área protegida para escrita seria o suficiente, isto separa e define o uso de processador ou MCU.

Atenciosamente.

**Comment by SnapRock** [comment]
**DÚVIDAS QUANTO AO FLUXO DE EXCEÇÃO.**

O PAF deverá corrigir o erro no documento, acionar o processo de apagar autorização retida no DAF, e submeter novamente o documento a todo fluxo para obter nova autorização, quando o processo “Solicitar autorização SEFAZ” receber como resposta uma Rejeição?

Este processo de apagar autorização retida no DAF, disponibiliza o contador monotônico para nova utilização?

E caso o processo de remoção não disponibilize o contador monotônico novamente, o PAF deverá inutilizar a numeração do documento recusado? Como fazer?

**Comment by paulosell** [comment]
@Juridico-afrac,
 
Primeiramente, agradecemos o interesse em contribuir com essa consulta pública. No momento estamos na fase de análise de todas as contribuições fornecidas e ficamos com dúvida em um dos pontos abordados.

Com relação ao problema de energia que pontuaram no item 4)b: poderiam nos fornecer mais detalhes para entendermos em quais versões do sistema operacional Windows e em quais cenários (ex: hibernação do host, retorno da hibernação do host, suspensão da energia da porta USB de dispositivos que requerem energia de forma intermitente, etc) o problema ocorre?
Existe alguma documentação do fabricante do sistema operacional que indique que o mesmo não opera corretamente com dispositivos USB CDC ou mesmo que podem ocorrer problemas quando usando controles de energia  (ex. suspensão seletiva USB do Windows 10) ou suspensão/hibernação do host?

**Comment by emersonmello** [comment]
@Juridico-afrac ,

Muito obrigado pelo interesse em participar dessa consulta pública. 

Com relação ao possível problema apresentado no item A.6), que reproduzo abaixo.

> Identificamos um possível problema em caso de erro de comunicação numa das etapas do processo de autorização do DF-e, sendo que não há especificação para um possível procedimento de recuperação. Acreditamos que seja necessária uma pequena revisão neste processo.

Fizemos uma revisão do procedimento descrito na Seção 5.2 e na Seção 5.2.4 da [Especificação Técnica de Requisitos do DAF - CP001](https://github.com/ifsc-lased/daf/blob/main/daf-consulta-publica.pdf) e não conseguimos identificar problemas que poderiam ser gerados diante de um possível erro de comunicação entre PAF e DAF, e que não foram tratados na presente especificação.

Por gentileza, poderiam fornecer mais detalhes sobre o problema identificado? Por exemplo: "o erro de comunicação após o DAF gerar a autorização e antes do PAF receber corretamente a mensagem 6 (Figura 5.3)". 

Obrigado.

**Comment by micsjc** [comment]
@emersonmello,

O problema ocorre justamente na condição que você citou: "o erro de comunicação após o DAF gerar a autorização e antes do PAF receber corretamente a mensagem 6 (Figura 5.3)". 

Nesse caso o DAF gerou corretamente a autorização, mas ela não foi recebida pelo PAF. Como o PAF não recebeu mensagem alguma, não há como saber se a autorização foi realizada. Como não há mecanismo de recuperação da autorização, o PAF terá que gerar outra, o que causará uma lacuna no sequencial dos DF-es emitidos.

O que fazer nesse caso? 

Att.

**Comment by emersonmello** [comment]
Olá @micsjc , 

Você seria uma outra conta associada à conta @Juridico-afrac? Desculpe-me, é que não vi uma identificação que me permitisse ligá-lo à AFRAC.

Obrigado.

**Comment by paulosell** [comment]
> Lúcia Correia da Silva
> Diretora Departamento Jurídico
> AFRAC - Associação Brasileira de Automação para o Comércio
> 
> Tendo em vista a publicação da Consulta Pública através do Ato DIAT Nº 047/2020 e a publicação das especificações de requisitos do equipamento DAF (Dispositivo Autorizados Fiscal), os Grupos Técnicos de Trabalho da AFRAC passaram a análise do mesmo e apresentam as seguintes sugestões e questionamentos:
> 
> **A. SUGESTÕES TÉCNICAS:**
> 
> **1)** Sobre Interface USB, relativos aos itens 2, 3, 3.4, 3.5, 3.7, 6.3:
> **a.** A interface USB é uma solução que obriga à presença física junto ao PDV, com conexão direta em painel ou através de cabos extensores e hubs. No caso de dispositivos PDV móveis, essa conexão deixa de ser possível, uma vez que dispositivos móveis possuem, tipicamente, apenas uma porta USB, com capacidade limitada de fornecimento de energia e mecanicamente inapropriada para conexão de um equipamento como apêndice.
> **b.** Entende-se que deveria ser permitido que a interface física pudesse ser implementada através de um dos padrões, além do USB: BLUETOOTH, WI-FI e ETHERNET.
> **c.** Como consequência, torna-se necessário permitir que o DAF possa ser acessado remotamente pelo PDV, podendo estar em local afastado, mas ainda fisicamente dentro do endereço do contribuinte.
> **d.** Em adição, em verdade, o fabricante poderia ainda escolher mais de uma interface ao mesmo tempo, podendo, por exemplo, que o DAF possa ser conectado diretamente à USB ou acessado via BLUETOOTH.
> **2)** Sobre o modelo de negócio 1 DAF para 1 PDV:
> **a.** Segundo o documento, todo terminal PDV, dotado de um aplicativo PAF, deve ter um DAF próprio.
> **b.** Sugerimos que um DAF seja compartilhado opcionalmente entre alguns PDVs, podemos ter um número máximo, como 5.
> **3)** Sobre a blindagem do equipamento:
> **a.** O documento utiliza o texto “malha” para se referir à blindagem no requisito 56.1. No entanto, isto encarece a solução, embora traga segurança adicional, neste cabe saber se a blindagem é um requisito mínimo. Sugerimos que poderia ser exposto apenas o requisito de segurança, ficando cada fabricante com a incumbência de demonstrar ao Órgão Técnico a eficácia da solução que está propondo.
> **4)** Sobre os Drivers de Comunicação CDC:
> **a.** Para as plataforma Linux, concordamos com a SEFAZ.
> **b.** Mas para plataforma Windows, essa categoria de drivers não apresenta uma solução nativa adequada pois os drivers oferecidos pelo Windows tem apresentado problemas em PDVs, em especial com relação à compatibilidade com as funções de suspensão e economia de energia deste sistema operacional.
> **c.** Desta forma, gostaríamos que, pensando na segurança do contribuinte, a SEFAZ abra para que Fabricantes possam fornecer Drivers próprios para comunicação com o DAF, respeitando claramente o requisito de exposição de porta serial para o PAF.
> **5)** Sobre a interface visual:
> **a.** Entendemos que a interface visual é muito importante para fins de suporte técnico do dispositivo e que limitar a apenas um LED possa restringir essa operação.
> **b.** Entendemos que, pensando no suporte, o fabricante deveria ter ao menos um indicador, conforme especificado no documento, mas mantendo ao seu critério a existência de outros indicadores auxiliares que possam contribuir para operação e suporte.
> **c.** A existência de outros indicadores auxiliares passa então a ser uma tomada de decisão estratégica do fabricante, em termos de custos e benefícios para o contribuinte.
> **d.** Outro ponto importante seria não definir a tecnologia do indicador. O mercado oferece diversas opções visuais, inclusive displays digitais. Restringir isso não parece ter conexão com segurança e deveria ser uma decisão de custo e benefício que cabe ao Fabricante.
> **6)** Identificamos um possível problema em caso de erro de comunicação numa das etapas do processo de autorização do DF-e, sendo que não há especificação para um possível procedimento de recuperação. Acreditamos que seja necessária uma pequena revisão neste processo.
> **7)** Sobre Bootloader e Programa do Modo Violado, gostaríamos de solicitar que houvesse a possibilidade de atualização também, assim como pode ser atualizado o aplicativo do DAF.
> 
> **B. QUESTIONAMENTOS LEVANTADOS:**
> 
> **1)** Qual seria a expectativa de mercado para o DAF em SC?
> **2)** Qual a previsão da infraestrutura de recebimento dos cupons estar pronta para o DAF?
> **3)** O estado de Santa Catarina considera que o fabricante que tiver pronto um protótipo poderia testar nesse tempo? Assim que esta infraestrutura estiver pronta e um contribuinte deseja instalar o DAF em produção, será possível ou somente em 2022?
> **4)** Quando estaria disponível o ambiente de desenvolvimento para que os fabricantes já possam validar o software básico?
> **5)** Já existe algum produto referência que os fabricantes pudessem ver o funcionamento? Caso positivo poderíamos ter acesso à documentação desse produto referência?
> **6)** Visando produzir um equipamento de menor custo, é necessário esclarecer quanto ao boot seguro e confirmar se é necessário o uso de processador com suporte a boot seguro e bootloader assinado ou se somente o bootloader em área protegida para escrita seria o suficiente, isto separa e define o uso de processador ou MCU.
> 
> Atenciosamente.

@Juridico-afrac,

Primeiramente, ficamos gratos pelo interesse em contribuir com essa consulta pública. Temos certeza que essa consulta pública servirá para aprimorar a versão final da especificação do DAF e todas sugestões recebidas foram de suma importância.

Indico que todas as contribuições recebidas, bem como os demais comentários registrados em cada contribuição, foram analisadas pela equipe técnica do IFSC e pela equipe de negócios da SEF.

Com relação as suas contribuições, temos os seguintes encaminhamentos:

**Sugestão A.1.**: Está em análise a inclusão da interface de comunicação Bluetooth para o DAF. Contudo, isso não será colocado na primeira versão da especificação do DAF.

**Sugestão A.2.**: Como indicado na resposta da [contribuição 1](https://github.com/ifsc-lased/daf/issues/1), na versão final desta especificação será adicionada a possibilidade de compartilhamento de um DAF por vários PDVs.

**Sugestão A.3.**: Para o projeto DAF foram analisadas as possibilidades que pudessem oferecer baixo custo final sem comprometer a segurança. Assim, chegou-se na proposta com malha de PCB de FR4 ou flexível, pois é um processo que consegue aliar alta segurança e baixo custo. Possibilita um processo de montagem rápido e barato, quando comparado com uma blindagem por Epoxi, por exemplo. Trata-se de um processo bem conhecido pelas montadoras e largamente utilizado em máquinas de cartão de crédito. Deste modo, a sugestão deste requisito ficar opcional ao fabricante não será acatada.

**Sugestão A.4.**: A especificação da interface de comunicação do DAF será flexibilizada , permitindo que o fabricante possa disponibilizar seu próprio driver para a comunicação do DAF com o PAF, desde que este não interfira nos drivers próprios do sistema operacional ou de drivers de outros fabricantes e respeite os demais requisitos da especificação do projeto.

**Sugestão A.5.**: Os estados do DAF foram discutidos no documento e apenas um LED foi suficiente para cobrir todas as informações necessárias para o suporte técnico. A escolha pelo uso de apenas um LED foi feita para diminuir o custo do equipamento, não apenas pelo componente em si, mas pelo tamanho do dispositivo. A ideia de padronizar o indicador visual é justamente não criar diferentes tipos de interface, em benefício do contribuinte, pois se o mesmo possuir DAFs de diferentes fabricantes, e todos compartilharem a mesma interface visual, ficará fácil para esse analisar a situação de cada um de seus DAFs. Deste modo, a sugestão para permitir diferentes interfaces visuais não será acatada.

**Sugestão A.6.**: Revisamos o procedimento descrito na Seção 5.2 e Seção 5.2.4 do documento e não conseguimos identificar problemas que poderiam ser gerados diante de um possível erro de comunicação entre PAF e DAF, e que não foram tratados na presente especificação. Se após o passo 5 da Figura 5.3 do documento ocorrer um problema de comunicação antes que o passo 6 seja concluído, então o PAF terá que reiniciar o processo descrito Seção 5.2. Como pode ser observado na Seção 5.2.4, o DAF ao receber uma solicitação de autorização, verifica, a partir do resumo criptográfico gerado sobre o XML completo do DF-e em questão, se já existe uma autorização para esse DF-e retida em sua MT. Se houver, então o DAF não emitirá uma nova autorização, mas sim, enviará a autorização já armazenada em sua memória.

**Sugestão A.7.**: Buscamos definir o bootloader e o programa do modo violado o mais simples possível, para facilitar o projeto, desenvolvimento e testes por parte dos fabricantes. Porém, o Bootloader e o modo inutilizado imutáveis são questões cruciais de segurança, Deste modo, a sugestão para possibilidade de atualização destes não pôde ser acatada.

**Sugestão B.**: Com exceção do item B.6., os itens apresentados nessa sugestão tratam de processos e decisões fora do escopo da presente consulta pública e poderão ser tratados pela SEF posteriormente.

**Sugestão B.6.**: O suporte ao boot seguro ou a existência de algum tipo de zona segura para o processamento do bootloader e do modo inutilizado é essencial para garantir as prerrogativas de segurança da proposta. A proposta indica o uso de um microcontrolador (MCU) e não de um microprocessador. O MCU tem todos os recursos na mesma pastilha (memória de dados, memória de programa e periféricos), sendo escolhido justamente devido ao custo de fabricação. Outro ponto que foi foco da especificação, é o uso de um MCU do tipo seguro. Esse possui periféricos para aceleração das rotinas criptográficas em hardware e também possui o recurso de boot seguro. Sendo assim, MCU seguro apresenta-se como a solução mais barata (entre US$ 5.00 e US$ 8.00) e que supre as necessidades da aplicação. Foram consultados diversos fabricantes de chips de forma a garantir que existissem várias opções no mercado com essa característica, evitando assim algum tipo de monopólio de um fabricante de chip.


Novamente, o nosso muito obrigado.
Projeto DAF

**Comment by paulosell** [comment]
> **DÚVIDAS QUANTO AO FLUXO DE EXCEÇÃO.**
> 
> O PAF deverá corrigir o erro no documento, acionar o processo de apagar autorização retida no DAF, e submeter novamente o documento a todo fluxo para obter nova autorização, quando o processo “Solicitar autorização SEFAZ” receber como resposta uma Rejeição?
> 
> Este processo de apagar autorização retida no DAF, disponibiliza o contador monotônico para nova utilização?
> 
> E caso o processo de remoção não disponibilize o contador monotônico novamente, o PAF deverá inutilizar a numeração do documento recusado? Como fazer?

@SnapRock, após receber e incorporar a autorização DAF ao DF-e, o PAF deverá solicitar a autorização junto à SEFAZ e posteriormente deverá solicitar o resultado da validação da autorização DAF, conforme serviço descrito na seção 8.10.1 do documento, junto à SEF. Com o resultado emitido pela SEF, será possível excluir a autorização retida na MT do DAF. Este processo deverá ocorrer independentemente da autorização de uso do DF-e, ou seja, mesmo que o documento tenha sido rejeitado pela SEFAZ autorizadora, será necessário obter o resultado da validação da autorização DAF junto à SEF. Deste modo, caso um DF-e não seja autorizado para uso pela SEFAZ, o PAF deverá fazer a correção do mesmo, de acordo com o motivo da rejeição, e o DAF deverá autorizar esse DF-e corrigido. Ambas as autorizações DAF (do DFe rejeitado e do DFe corrigido) deverão ser removidas posteriormente da MT do DAF. Em outros termos, um DF-e pode obter mais de uma autorização DAF, uma vez que as autorizações emitidas pelo DAF são armazenadas em sua MT de acordo com o resumo criptográfico gerado sobre o XML completo do DF-e. Assim, ao solicitar a autorização de um DF-e que foi modificado, como em casos de correções por rejeições, o DAF considerará como um novo DF-e. Logo, o contador monotônico é incrementado novamente.
